# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TransmissionObjectItem(object):

    def __init__(self, name=None, all=None, dmlOp=None, ddlOp=None, tables=None):
        """
        :param name: (Optional) 目标 Schema 名称
        :param all: (Optional) 是否传输该 Scheam 下所有 Table
        :param dmlOp: (Optional) 传输的 DML 操作列表
        :param ddlOp: (Optional) 传输的 DDL 操作列表
        :param tables: (Optional) 
        """

        self.name = name
        self.all = all
        self.dmlOp = dmlOp
        self.ddlOp = ddlOp
        self.tables = tables
