# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class NodeNetwork(object):

    def __init__(self, podSubnetId=None, nodeSubnetId=None, serviceSubnetId=None, servicePublicSubnetId=None, nodeNetworkCidr=None, vpcId=None):
        """
        :param podSubnetId: (Optional) pod子网的id
        :param nodeSubnetId: (Optional) node子网的id
        :param serviceSubnetId: (Optional) service子网的id
        :param servicePublicSubnetId: (Optional) service关联LB的具有公网访问能力的子网id
        :param nodeNetworkCidr: (Optional) node的cidr
        :param vpcId: (Optional) vpc id
        """

        self.podSubnetId = podSubnetId
        self.nodeSubnetId = nodeSubnetId
        self.serviceSubnetId = serviceSubnetId
        self.servicePublicSubnetId = servicePublicSubnetId
        self.nodeNetworkCidr = nodeNetworkCidr
        self.vpcId = vpcId
