# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DescribeSystemRequest(JDCloudRequest):
    """
    根据系统 ID 查询系统详情
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DescribeSystemRequest, self).__init__(
            '/system/{systemId}', 'GET', header, version)
        self.parameters = parameters


class DescribeSystemParameters(object):

    def __init__(self,systemId):
        """
        :param systemId: 系统ID
        """

        self.systemId = systemId

