# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class GetPackageDownloadInfoRequest(JDCloudRequest):
    """
    获取指定应用下制品包的下载信息，包含名称、版本及预签名下载地址（preSignedUrl）。 调用方使用返回的 preSignedUrl 自行下载文件（该地址有鉴权、有效期有限）。
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(GetPackageDownloadInfoRequest, self).__init__(
            '/app/{appId}/package/{packageId}:downloadInfo', 'GET', header, version)
        self.parameters = parameters


class GetPackageDownloadInfoParameters(object):

    def __init__(self,appId, packageId):
        """
        :param appId: 应用ID，E.g.，app-123456789
        :param packageId: 制品包ID，E.g.，10086
        """

        self.appId = appId
        self.packageId = packageId

