# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class LinkPackageRequest(JDCloudRequest):
    """
    将制品包与指定应用建立关联，返回流水线ID
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(LinkPackageRequest, self).__init__(
            '/app/{appId}:linkPackage', 'POST', header, version)
        self.parameters = parameters


class LinkPackageParameters(object):

    def __init__(self,appId, ):
        """
        :param appId: 应用ID，E.g.，app-123456789
        """

        self.appId = appId
        self.name = None
        self.version = None
        self.desc = None
        self.env = None
        self.url = None

    def setName(self, name):
        """
        :param name: (Optional) 制品包名称，E.g.，my-app-package
        """
        self.name = name

    def setVersion(self, version):
        """
        :param version: (Optional) 制品包版本号，E.g.，v1.0.0
        """
        self.version = version

    def setDesc(self, desc):
        """
        :param desc: (Optional) 制品包描述，E.g.，一次构建产物
        """
        self.desc = desc

    def setEnv(self, env):
        """
        :param env: (Optional) 环境标识，E.g.，prod
        """
        self.env = env

    def setUrl(self, url):
        """
        :param url: (Optional) 制品包下载地址，E.g.，https://repo.jdcloud.com/artifact/my-app-package-v1.0.0.tar.gz
        """
        self.url = url

