# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class CreateTokenRequest(JDCloudRequest):
    """
    生成token-用户加入房间时携带token校验通过后方能加入

    """

    def __init__(self, parameters, header=None, version="v1"):
        super(CreateTokenRequest, self).__init__(
            '/createToken', 'POST', header, version)
        self.parameters = parameters


class CreateTokenParameters(object):

    def __init__(self, ):
        """
        """

        self.appId = None
        self.appKey = None
        self.userId = None
        self.userRoomId = None
        self.timestamp = None

    def setAppId(self, appId):
        """
        :param appId: (Optional) appId
        """
        self.appId = appId

    def setAppKey(self, appKey):
        """
        :param appKey: (Optional) appKey
        """
        self.appKey = appKey

    def setUserId(self, userId):
        """
        :param userId: (Optional) 用户id
        """
        self.userId = userId

    def setUserRoomId(self, userRoomId):
        """
        :param userRoomId: (Optional) 业务接入方定义的且在JRTC系统内注册过的房间号
        """
        self.userRoomId = userRoomId

    def setTimestamp(self, timestamp):
        """
        :param timestamp: (Optional) 时间戳-毫秒
        """
        self.timestamp = timestamp

