# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class ManageHubClusterUpdateRequest(JDCloudRequest):
    """
    更新集群
    """

    def __init__(self, parameters, header=None, version="v2"):
        super(ManageHubClusterUpdateRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/manageHubClusterUpdate', 'POST', header, version)
        self.parameters = parameters


class ManageHubClusterUpdateParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.clusterId = None
        self.clusterCode = None
        self.clusterName = None
        self.remark = None

    def setClusterId(self, clusterId):
        """
        :param clusterId: (Optional) 集群ID
        """
        self.clusterId = clusterId

    def setClusterCode(self, clusterCode):
        """
        :param clusterCode: (Optional) 集群编码
        """
        self.clusterCode = clusterCode

    def setClusterName(self, clusterName):
        """
        :param clusterName: (Optional) 集群名称
        """
        self.clusterName = clusterName

    def setRemark(self, remark):
        """
        :param remark: (Optional) 备注
        """
        self.remark = remark

