# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class RotorSupplementPlanCreateRequest(JDCloudRequest):
    """
    创建补数方案
    """

    def __init__(self, parameters, header=None, version="v2"):
        super(RotorSupplementPlanCreateRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/rotorSupplementPlanCreate', 'POST', header, version)
        self.parameters = parameters


class RotorSupplementPlanCreateParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.name = None
        self.method = None
        self.txDateRanges = None
        self.groupNums = None
        self.timeRangeStart = None
        self.timeRangeEnd = None
        self.order = None
        self.resourceGroupStrategy = None
        self.calculateTaskResourceGroup = None
        self.integrationTaskResourceGroup = None
        self.remark = None
        self.taskIds = None
        self.rootTaskId = None
        self.downStreamTaskIds = None

    def setName(self, name):
        """
        :param name: (Optional) 补数方案名称
        """
        self.name = name

    def setMethod(self, method):
        """
        :param method: (Optional) 补数方式：batch-批量补数、chain-链路补数
        """
        self.method = method

    def setTxDateRanges(self, txDateRanges):
        """
        :param txDateRanges: (Optional) 补数数据日期范围列表
        """
        self.txDateRanges = txDateRanges

    def setGroupNums(self, groupNums):
        """
        :param groupNums: (Optional) 并行分组数量
        """
        self.groupNums = groupNums

    def setTimeRangeStart(self, timeRangeStart):
        """
        :param timeRangeStart: (Optional) 时间范围-开始时间（HH:mm）
        """
        self.timeRangeStart = timeRangeStart

    def setTimeRangeEnd(self, timeRangeEnd):
        """
        :param timeRangeEnd: (Optional) 时间范围-结束时间（HH:mm）
        """
        self.timeRangeEnd = timeRangeEnd

    def setOrder(self, order):
        """
        :param order: (Optional) 补数顺序：asc-正序、desc-倒序
        """
        self.order = order

    def setResourceGroupStrategy(self, resourceGroupStrategy):
        """
        :param resourceGroupStrategy: (Optional) 补数资源组策略：default-跟随任务配置、specify-指定资源组
        """
        self.resourceGroupStrategy = resourceGroupStrategy

    def setCalculateTaskResourceGroup(self, calculateTaskResourceGroup):
        """
        :param calculateTaskResourceGroup: (Optional) 计算任务资源组编码：仅当 resourceGroupStrategy 指定为 specify 时有效
        """
        self.calculateTaskResourceGroup = calculateTaskResourceGroup

    def setIntegrationTaskResourceGroup(self, integrationTaskResourceGroup):
        """
        :param integrationTaskResourceGroup: (Optional) 集成任务资源组：仅当 resourceGroupStrategy 指定为 specify 时有效
        """
        self.integrationTaskResourceGroup = integrationTaskResourceGroup

    def setRemark(self, remark):
        """
        :param remark: (Optional) 补数原因
        """
        self.remark = remark

    def setTaskIds(self, taskIds):
        """
        :param taskIds: (Optional) 补数任务ID列表：批量补数时必传
        """
        self.taskIds = taskIds

    def setRootTaskId(self, rootTaskId):
        """
        :param rootTaskId: (Optional) 根任务ID：链路补数时必传
        """
        self.rootTaskId = rootTaskId

    def setDownStreamTaskIds(self, downStreamTaskIds):
        """
        :param downStreamTaskIds: (Optional) 下游任务ID列表：链路补数时必传
        """
        self.downStreamTaskIds = downStreamTaskIds

