# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class UranusTaskParseScriptContentSystemParamRequest(JDCloudRequest):
    """
    解析脚本内容中的系统参数
    """

    def __init__(self, parameters, header=None, version="v2"):
        super(UranusTaskParseScriptContentSystemParamRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/uranusTaskParseScriptContentSystemParam', 'POST', header, version)
        self.parameters = parameters


class UranusTaskParseScriptContentSystemParamParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.taskDraftId = None
        self.content = None
        self.currentTime = None

    def setTaskDraftId(self, taskDraftId):
        """
        :param taskDraftId: (Optional) 任务草稿id
        """
        self.taskDraftId = taskDraftId

    def setContent(self, content):
        """
        :param content: (Optional) 任务脚本内容
        """
        self.content = content

    def setCurrentTime(self, currentTime):
        """
        :param currentTime: (Optional) 自定义的系统当前时间，例如"2025-05-15 00:00"
        """
        self.currentTime = currentTime

