# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TranscodeTaskObject(object):

    def __init__(self, taskId=None, name=None, mediaType=None, status=None, progress=None, size=None, templateId=None, bitrate=None, codec=None, format=None, width=None, height=None, fps=None, createTime=None, updateTime=None):
        """
        :param taskId: (Optional) 任务ID
        :param name: (Optional) 码率名称
        :param mediaType: (Optional) 媒体类型
        :param status: (Optional) 状态
        :param progress: (Optional) 进度
        :param size: (Optional) 文件大小
        :param templateId: (Optional) 转码模板ID
        :param bitrate: (Optional) 码率
        :param codec: (Optional) 编码格式
        :param format: (Optional) 封装格式
        :param width: (Optional) 宽度
        :param height: (Optional) 高度
        :param fps: (Optional) 帧率
        :param createTime: (Optional) 创建时间
        :param updateTime: (Optional) 更新时间
        """

        self.taskId = taskId
        self.name = name
        self.mediaType = mediaType
        self.status = status
        self.progress = progress
        self.size = size
        self.templateId = templateId
        self.bitrate = bitrate
        self.codec = codec
        self.format = format
        self.width = width
        self.height = height
        self.fps = fps
        self.createTime = createTime
        self.updateTime = updateTime
