# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class RenewInstanceParam(object):

    def __init__(self, appCode, serviceCode, timeUnit, timeSpan, sign, instanceIds, unifyDate=None, autoPay=None, returnURL=None):
        """
        :param appCode:  业务线
        :param serviceCode:  产品线
        :param timeUnit:  时间单位 1:小时 2:天 3:月 4:年
        :param timeSpan:  时长
        :param sign:  签名 md5(pin+serviceCode+key)
        :param instanceIds:  待续费资源id列表,英文逗号分隔
        :param unifyDate: (Optional) 是否统一续费到期日续费 1-是 0-否（默认为0）
        :param autoPay: (Optional) 是否自动支付 true-是 false-否（默认为true）
        :param returnURL: (Optional) 回调地址
        """

        self.appCode = appCode
        self.serviceCode = serviceCode
        self.timeUnit = timeUnit
        self.timeSpan = timeSpan
        self.sign = sign
        self.instanceIds = instanceIds
        self.unifyDate = unifyDate
        self.autoPay = autoPay
        self.returnURL = returnURL
