# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class BandData(object):

    def __init__(self, monthly95=None, monthlyPeak=None, dailyPeaks=None, details=None):
        """
        :param monthly95: (Optional) 月95(MB)
        :param monthlyPeak: (Optional) 月峰值(MB)
        :param dailyPeaks: (Optional) 日峰值(MB)
        :param details: (Optional) 5分钟详情
        """

        self.monthly95 = monthly95
        self.monthlyPeak = monthlyPeak
        self.dailyPeaks = dailyPeaks
        self.details = details
