# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class OridbwTableItem(object):

    def __init__(self, groupByname=None, domainType=None, oriflowPercent=None, oripvPercent=None, avgbandwidth=None, avgoribandwidth=None, oriTopTimeStamp=None, pv=None, oripv=None, flow=None, oriflow=None):
        """
        :param groupByname: (Optional) 
        :param domainType: (Optional) 
        :param oriflowPercent: (Optional) 
        :param oripvPercent: (Optional) 
        :param avgbandwidth: (Optional) 
        :param avgoribandwidth: (Optional) 
        :param oriTopTimeStamp: (Optional) 
        :param pv: (Optional) 
        :param oripv: (Optional) 
        :param flow: (Optional) 
        :param oriflow: (Optional) 
        """

        self.groupByname = groupByname
        self.domainType = domainType
        self.oriflowPercent = oriflowPercent
        self.oripvPercent = oripvPercent
        self.avgbandwidth = avgbandwidth
        self.avgoribandwidth = avgoribandwidth
        self.oriTopTimeStamp = oriTopTimeStamp
        self.pv = pv
        self.oripv = oripv
        self.flow = flow
        self.oriflow = oriflow
