# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class PvItem(object):

    def __init__(self, timeUtc=None, totalPv=None, attackPv=None):
        """
        :param timeUtc: (Optional) UTC时间，格式为:yyyy-MM-dd'T'HH:mm:ss'Z'，示例:2018-10-21T10:00:00Z
        :param totalPv: (Optional) 总请求量
        :param attackPv: (Optional) 攻击请求量
        """

        self.timeUtc = timeUtc
        self.totalPv = totalPv
        self.attackPv = attackPv
