# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class SubmitTranscodeJobRequest(JDCloudRequest):
    """
    提交转码作业
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(SubmitTranscodeJobRequest, self).__init__(
            '/transcodeTasks:submitJob', 'POST', header, version)
        self.parameters = parameters


class SubmitTranscodeJobParameters(object):

    def __init__(self, ):
        """
        """

        self.videoId = None
        self.templateIds = None
        self.watermarkIds = None

    def setVideoId(self, videoId):
        """
        :param videoId: (Optional) 视频ID
        """
        self.videoId = videoId

    def setTemplateIds(self, templateIds):
        """
        :param templateIds: (Optional) 转码模板ID列表
        """
        self.templateIds = templateIds

    def setWatermarkIds(self, watermarkIds):
        """
        :param watermarkIds: (Optional) 水印ID列表
        """
        self.watermarkIds = watermarkIds

