# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ContactPersonVo(object):

    def __init__(self, personId=None, pin=None, userName=None, email=None, mobile=None, mobileValid=None, emailValid=None, isMain=None, isSelf=None, contactGroups=None):
        """
        :param personId: (Optional) 联系人ID
        :param pin: (Optional) 用户pin(创建人)
        :param userName: (Optional) 用户名
        :param email: (Optional) 邮箱
        :param mobile: (Optional) 手机号
        :param mobileValid: (Optional) 用户手机号是否有效（1-有效 0-无效）
        :param emailValid: (Optional) 用户邮箱是否有效（1-有效 0-无效）
        :param isMain: (Optional) 是否为主联系人
        :param isSelf: (Optional) 1:账号联系人;2:非账号联系人
        :param contactGroups: (Optional) 
        """

        self.personId = personId
        self.pin = pin
        self.userName = userName
        self.email = email
        self.mobile = mobile
        self.mobileValid = mobileValid
        self.emailValid = emailValid
        self.isMain = isMain
        self.isSelf = isSelf
        self.contactGroups = contactGroups
