# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class UserSellerVo(object):

    def __init__(self, erp=None, dept=None, email=None, mobile=None):
        """
        :param erp: (Optional) 销售员erp
        :param dept: (Optional) 部门信息
        :param email: (Optional) 公司邮箱
        :param mobile: (Optional) 手机号
        """

        self.erp = erp
        self.dept = dept
        self.email = email
        self.mobile = mobile
