# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AiOpsRayTaskInstancePageVO(object):

    def __init__(self, total=None, pageNo=None, pageSize=None, data=None):
        """
        :param total: (Optional) 总条数
        :param pageNo: (Optional) 当前页码
        :param pageSize: (Optional) 每页条数
        :param data: (Optional) 数据列表
        """

        self.total = total
        self.pageNo = pageNo
        self.pageSize = pageSize
        self.data = data
