# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AiOpsRayTaskInstancePodDetailVO(object):

    def __init__(self, podName=None, status=None, cpuRequest=None, memoryRequest=None, gpuRequest=None, createTimestamp=None, restartCount=None, clusterCode=None, clusterId=None, events=None, containers=None):
        """
        :param podName: (Optional) Pod 名称
        :param status: (Optional) Pod 状态
        :param cpuRequest: (Optional) 请求 CPU
        :param memoryRequest: (Optional) 请求内存
        :param gpuRequest: (Optional) 请求 GPU
        :param createTimestamp: (Optional) 创建时间（时间戳，毫秒）
        :param restartCount: (Optional) 重启次数
        :param clusterCode: (Optional) 集群编码
        :param clusterId: (Optional) 集群 ID
        :param events: (Optional) 事件列表
        :param containers: (Optional) 容器列表
        """

        self.podName = podName
        self.status = status
        self.cpuRequest = cpuRequest
        self.memoryRequest = memoryRequest
        self.gpuRequest = gpuRequest
        self.createTimestamp = createTimestamp
        self.restartCount = restartCount
        self.clusterCode = clusterCode
        self.clusterId = clusterId
        self.events = events
        self.containers = containers
