# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AnalyzeQueryRecordsParam(object):

    def __init__(self, pageNum=None, pageSize=None, clusterId=None, status=None, startTime=None, endTime=None, scriptPath=None, orderBy=None, asc=None):
        """
        :param pageNum: (Optional) 页码，从1开始
        :param pageSize: (Optional) 每页大小
        :param clusterId: (Optional) 集群ID
        :param status: (Optional) {SUBMITTED=已提交, RUNNING=运行中, COMPLETED=已完成, FAILED=失败, CANCELLED=已取消, TIMEOUT=超时}
        :param startTime: (Optional) 开始时间
        :param endTime: (Optional) 结束时间
        :param scriptPath: (Optional) 脚本路径（如果指定，则只查询该脚本的执行记录）
        :param orderBy: (Optional) 排序字段
        :param asc: (Optional) 是否升序
        """

        self.pageNum = pageNum
        self.pageSize = pageSize
        self.clusterId = clusterId
        self.status = status
        self.startTime = startTime
        self.endTime = endTime
        self.scriptPath = scriptPath
        self.orderBy = orderBy
        self.asc = asc
