# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ModifyTableReq(object):

    def __init__(self, companyCode=None, catalogName=None, schemaName=None, tableName=None, metaType=None, tableChangeReqs=None):
        """
        :param companyCode: (Optional) 租户code
        :param catalogName: (Optional) catalog名称
        :param schemaName: (Optional) schema名称
        :param tableName: (Optional) 表名称
        :param metaType: (Optional) 元数据类型(iceberg/lance/fileset/paimon)
        :param tableChangeReqs: (Optional) 
        """

        self.companyCode = companyCode
        self.catalogName = catalogName
        self.schemaName = schemaName
        self.tableName = tableName
        self.metaType = metaType
        self.tableChangeReqs = tableChangeReqs
