# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class PodMachineDetailVO(object):

    def __init__(self, id=None, machineId=None, machineName=None, machineType=None, regionId=None, az=None, innerIp=None, createTime=None, updateTime=None, outerIp=None, status=None, statusInfo=None, envConfigs=None, storageMountConfigs=None, workDir=None, appLinks=None, jupyterLink=None, alertConfig=None):
        """
        :param id: (Optional) ID
        :param machineId: (Optional) 开发机ID
        :param machineName: (Optional) pod开发机名称
        :param machineType: (Optional) 开发机类型(Pod/云主机)
        :param regionId: (Optional) 地域
        :param az: (Optional) 可用区
        :param innerIp: (Optional) 内网IP(Pod开发机为空)
        :param createTime: (Optional) 创建时间
        :param updateTime: (Optional) 更新时间
        :param outerIp: (Optional) 外网IP(Pod开发机为空)
        :param status: (Optional) 状态
        :param statusInfo: (Optional) 状态信息
        :param envConfigs: (Optional) 环境变量配置
        :param storageMountConfigs: (Optional) 存储挂载配置(pod开发机器在k8s集群的pod中挂载)
        :param workDir: (Optional) 工作目录
        :param appLinks: (Optional) 应用链接配置 例如 JupyterLab, ray dashboard, SparkUI 等, 一般用于在集群应用启动后提供访问入口
        :param jupyterLink: (Optional) Jupyter链接, 单独提取给前端使用
        :param alertConfig: (Optional) 
        """

        self.id = id
        self.machineId = machineId
        self.machineName = machineName
        self.machineType = machineType
        self.regionId = regionId
        self.az = az
        self.innerIp = innerIp
        self.createTime = createTime
        self.updateTime = updateTime
        self.outerIp = outerIp
        self.status = status
        self.statusInfo = statusInfo
        self.envConfigs = envConfigs
        self.storageMountConfigs = storageMountConfigs
        self.workDir = workDir
        self.appLinks = appLinks
        self.jupyterLink = jupyterLink
        self.alertConfig = alertConfig
