# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TableBriefInfoVo(object):

    def __init__(self, companyCode=None, catalogName=None, schemaName=None, tableName=None, comment=None, metaType=None, hasChildren=None, view=None, filesetId=None, owner=None, tags=None):
        """
        :param companyCode: (Optional) 租户code
        :param catalogName: (Optional) catalog名称
        :param schemaName: (Optional) schema名称
        :param tableName: (Optional) 表名称，如果是fileset，就是fileset名称
        :param comment: (Optional) 描述
        :param metaType: (Optional) 元数据类型
        :param hasChildren: (Optional) 是否有子节点
        :param view: (Optional) 前端可以用来展示时的接口（前端左侧目录树的检索接口时使用）
        :param filesetId: (Optional) filesetId，当为fileset类型时有值
        :param owner: (Optional) 所有人
        :param tags: (Optional) 标签列表(含从 schema/catalog 继承),每条带 source 标识来源(CATALOG/SCHEMA/TABLE/FILESET/MODEL)。同名标签若同时挂在多个层级会作为多条独立记录返回
        """

        self.companyCode = companyCode
        self.catalogName = catalogName
        self.schemaName = schemaName
        self.tableName = tableName
        self.comment = comment
        self.metaType = metaType
        self.hasChildren = hasChildren
        self.view = view
        self.filesetId = filesetId
        self.owner = owner
        self.tags = tags
