# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TaskCreateOrUpdateParam(object):

    def __init__(self, id=None, name=None, type=None, description=None, ownerPins=None, imageConfig=None, bootCommand=None, lmceConfigYaml=None, envConfigs=None, storageMountConfigs=None, queue=None, queueType=None, rayConfig=None, sparkConfig=None, enablePrompt=None, podPriority=None, alertConfig=None):
        """
        :param id: (Optional) 任务ID（更新时必传，创建时不传）
        :param name: (Optional) 名称
        :param type: (Optional) 类型
        :param description: (Optional) 描述
        :param ownerPins: (Optional) 负责人
        :param imageConfig: (Optional) 镜像配置
        :param bootCommand: (Optional) Ray 任务 - 启动命令
        :param lmceConfigYaml: (Optional) Lmce 任务 - Yaml配置
        :param envConfigs: (Optional) 环境变量
        :param storageMountConfigs: (Optional) 存储挂载配置
        :param queue: (Optional) 资源队列
        :param queueType: (Optional) 队列类型
        :param rayConfig: (Optional) Ray配置（仅Ray任务有该属性）
        :param sparkConfig: (Optional) Spark配置（仅Spark任务有该属性）
        :param enablePrompt: (Optional) 是否开启队列内抢占
        :param podPriority: (Optional) 抢占优先级：HIGH、MEDIUM、LOW
        :param alertConfig: (Optional) 告警配置
        """

        self.id = id
        self.name = name
        self.type = type
        self.description = description
        self.ownerPins = ownerPins
        self.imageConfig = imageConfig
        self.bootCommand = bootCommand
        self.lmceConfigYaml = lmceConfigYaml
        self.envConfigs = envConfigs
        self.storageMountConfigs = storageMountConfigs
        self.queue = queue
        self.queueType = queueType
        self.rayConfig = rayConfig
        self.sparkConfig = sparkConfig
        self.enablePrompt = enablePrompt
        self.podPriority = podPriority
        self.alertConfig = alertConfig
