# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class WorkspaceUserReq(object):

    def __init__(self, pageNum=None, pageSize=None, id=None, userName=None, nickName=None, userPin=None, workspaceCode=None, companyCode=None, regionId=None):
        """
        :param pageNum: (Optional) 当前页码
        :param pageSize: (Optional) 每页显示的条数
        :param id: (Optional) 工作空间id（非用户定义id）
        :param userName: (Optional) 用户名
        :param nickName: (Optional) 昵称
        :param userPin: (Optional) 用户pin
        :param workspaceCode: (Optional) 工作空间code
        :param companyCode: (Optional) 租户code
        :param regionId: (Optional) 地域ID
        """

        self.pageNum = pageNum
        self.pageSize = pageSize
        self.id = id
        self.userName = userName
        self.nickName = nickName
        self.userPin = userPin
        self.workspaceCode = workspaceCode
        self.companyCode = companyCode
        self.regionId = regionId
