# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class Raid(object):

    def __init__(self, volumeType=None, volumeDetail=None, raidTypeId=None, raidType=None, deviceType=None, description=None):
        """
        :param volumeType: (Optional) 磁盘类型, 如 system/data
        :param volumeDetail: (Optional) 设备详情
        :param raidTypeId: (Optional) RAID类型ID
        :param raidType: (Optional) RAID类型, 如 NORAID, RAID0, RAID1
        :param deviceType: (Optional) 云物理服务器类型, 如 edcps.c.normal1
        :param description: (Optional) RAID类型描述
        """

        self.volumeType = volumeType
        self.volumeDetail = volumeDetail
        self.raidTypeId = raidTypeId
        self.raidType = raidType
        self.deviceType = deviceType
        self.description = description
