# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DescribeCustomPagesRequest(JDCloudRequest):
    """
    查询自定义页面列表
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DescribeCustomPagesRequest, self).__init__(
            '/regions/{regionId}/instances/{instanceId}/customPages', 'GET', header, version)
        self.parameters = parameters


class DescribeCustomPagesParameters(object):

    def __init__(self, regionId, instanceId, ):
        """
        :param regionId: 区域 ID, 高防不区分区域, 传 cn-north-1 即可
        :param instanceId: 实例 ID
        """

        self.regionId = regionId
        self.instanceId = instanceId
        self.status = None

    def setStatus(self, status):
        """
        :param status: (Optional) 自定义页面状态, 可取值approving: 审批中, refused: 审批不通过, approved: 审批通过, 为空时查询全部
        """
        self.status = status

