# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ListProxycacheUrl(object):

    def __init__(self, id=None, uri=None, proto=None, disable=None, matchOp=None, updateTime=None):
        """
        :param id: (Optional) 规则id
        :param uri: (Optional) 缓存的uri
        :param proto: (Optional) 协议
        :param disable: (Optional) 0-缓存生效，1-缓存不生效
        :param matchOp: (Optional) 匹配模式
        :param updateTime: (Optional) 更新时间，s时间戳
        """

        self.id = id
        self.uri = uri
        self.proto = proto
        self.disable = disable
        self.matchOp = matchOp
        self.updateTime = updateTime
