# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class SetIpbanUsrReq(object):

    def __init__(self, wafInstanceId, domain, ruleName, detectTime, threshold, ipbanTime, disable, action, ):
        """
        :param wafInstanceId:  WAF实例id
        :param domain:  域名
        :param ruleName:  规则名
        :param detectTime:  检测时间 单位秒， 限制[60-600]
        :param threshold:  封禁阈值，限制[1-20000]
        :param ipbanTime:  封禁时间，限制[1-86400]
        :param disable:  0-使用中 1-禁用
        :param action:  动作配置
        """

        self.wafInstanceId = wafInstanceId
        self.domain = domain
        self.ruleName = ruleName
        self.detectTime = detectTime
        self.threshold = threshold
        self.ipbanTime = ipbanTime
        self.disable = disable
        self.action = action
