# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class UserPolicyWafDomain(object):

    def __init__(self, wafInstanceId=None, nickName=None, domains=None):
        """
        :param wafInstanceId: (Optional) 自定义规则组应用的实例
        :param nickName: (Optional) 自定义规则组应用的实例nickName
        :param domains: (Optional) 自定义规则组应用的域名
        """

        self.wafInstanceId = wafInstanceId
        self.nickName = nickName
        self.domains = domains
