# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class DescribedAlarm(object):

    def __init__(self, calculateUnit=None, calculation=None, createTime=None, downSample=None, enabled=None, id=None, metric=None, metricName=None, noticeLevel=None, noticePeriod=None, operation=None, period=None, region=None, resourceId=None, serviceCode=None, status=None, tags=None, threshold=None, times=None):
        """
        :param calculateUnit: (Optional) 计算单位
        :param calculation: (Optional) 统计方法：平均值=avg、最大值=max、最小值=min
        :param createTime: (Optional) 创建时间
        :param downSample: (Optional) 降采样方法
        :param enabled: (Optional) 是否启用
        :param id: (Optional) 报警规则ID
        :param metric: (Optional) 监控项
        :param metricName: (Optional) 监控项名称
        :param noticeLevel: (Optional) 
        :param noticePeriod: (Optional) 告警周期
        :param operation: (Optional) gt, gte, lt, lte, eq, ne
        :param period: (Optional) 统计周期（单位：分钟）
        :param region: (Optional) 地域信息
        :param resourceId: (Optional) 资源id
        :param serviceCode: (Optional) 产品线编码
        :param status: (Optional) 监控项状态：1正常，2告警，4数据不足
        :param tags: (Optional) 标签
        :param threshold: (Optional) 告警阈值
        :param times: (Optional) 告警次数
        """

        self.calculateUnit = calculateUnit
        self.calculation = calculation
        self.createTime = createTime
        self.downSample = downSample
        self.enabled = enabled
        self.id = id
        self.metric = metric
        self.metricName = metricName
        self.noticeLevel = noticeLevel
        self.noticePeriod = noticePeriod
        self.operation = operation
        self.period = period
        self.region = region
        self.resourceId = resourceId
        self.serviceCode = serviceCode
        self.status = status
        self.tags = tags
        self.threshold = threshold
        self.times = times
