# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AppQueryResultItem(object):

    def __init__(self, clientId=None, clientName=None, tokenEndpointAuthMethod=None, grantTypes=None, responseTypes=None, redirectUris=None, clientUri=None, logoUri=None, tosUri=None, policyUri=None, scope=None, jwksUri=None, jwks=None, contacts=None, extension=None, accessTokenValiditySeconds=None, refreshTokenValiditySeconds=None, multiTenant=None, secretUpdateTime=None, updateTime=None, createTime=None, account=None, userType=None, state=None):
        """
        :param clientId: (Optional) 应用
        :param clientName: (Optional) 应用名
        :param tokenEndpointAuthMethod: (Optional) tokenEndpointAuthMethod
        :param grantTypes: (Optional) grantTypes
        :param responseTypes: (Optional) responseTypes
        :param redirectUris: (Optional) redirectUris
        :param clientUri: (Optional) clientUri
        :param logoUri: (Optional) logoUri
        :param tosUri: (Optional) tosUri
        :param policyUri: (Optional) policyUri
        :param scope: (Optional) scope
        :param jwksUri: (Optional) jwksUri
        :param jwks: (Optional) jwks
        :param contacts: (Optional) contacts
        :param extension: (Optional) extension
        :param accessTokenValiditySeconds: (Optional) accessTokenValiditySeconds
        :param refreshTokenValiditySeconds: (Optional) refreshTokenValiditySeconds
        :param multiTenant: (Optional) multiTenant
        :param secretUpdateTime: (Optional) secretUpdateTime
        :param updateTime: (Optional) updateTime
        :param createTime: (Optional) createTime
        :param account: (Optional) account
        :param userType: (Optional) userType
        :param state: (Optional) state
        """

        self.clientId = clientId
        self.clientName = clientName
        self.tokenEndpointAuthMethod = tokenEndpointAuthMethod
        self.grantTypes = grantTypes
        self.responseTypes = responseTypes
        self.redirectUris = redirectUris
        self.clientUri = clientUri
        self.logoUri = logoUri
        self.tosUri = tosUri
        self.policyUri = policyUri
        self.scope = scope
        self.jwksUri = jwksUri
        self.jwks = jwks
        self.contacts = contacts
        self.extension = extension
        self.accessTokenValiditySeconds = accessTokenValiditySeconds
        self.refreshTokenValiditySeconds = refreshTokenValiditySeconds
        self.multiTenant = multiTenant
        self.secretUpdateTime = secretUpdateTime
        self.updateTime = updateTime
        self.createTime = createTime
        self.account = account
        self.userType = userType
        self.state = state
