# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class CreateEventRequest(JDCloudRequest):
    """
    创建一个 event
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(CreateEventRequest, self).__init__(
            '/regions/{regionId}/memories/{memoryId}/events', 'POST', header, version)
        self.parameters = parameters


class CreateEventParameters(object):

    def __init__(self,regionId, pin, requestId, actor, memoryId, messages, ):
        """
        :param regionId: 地域 Id
        :param pin: 用户（主、子）账号。base64编码。格式为：base64(subuser-pin) @ base64(owner-pin)。@前后有空格。若不支持主子账号，则不需要@，格式为 base64(owner-pin)
in: header
        :param requestId: 请求ID
in: header
        :param actor: 触发用户
        :param memoryId: 内存id
        :param messages: 消息内容
        """

        self.regionId = regionId
        self.erpAccount = None
        self.pin = pin
        self.requestId = requestId
        self.actor = actor
        self.infer = None
        self.memoryId = memoryId
        self.messages = messages
        self.sessionId = None

    def setErpAccount(self, erpAccount):
        """
        :param erpAccount: (Optional) x-jdcloud-erp   base64(username)
in: header
        """
        self.erpAccount = erpAccount

    def setInfer(self, infer):
        """
        :param infer: (Optional) 是否进行推理并保存长期记忆。 默认为 true。
        """
        self.infer = infer

    def setSessionId(self, sessionId):
        """
        :param sessionId: (Optional) 会话ID： 传入会话 ID 的，会保存为临时记忆
        """
        self.sessionId = sessionId

