# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class CreateBackupSynchronicityRequest(JDCloudRequest):
    """
    创建跨区域备份同步服务
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(CreateBackupSynchronicityRequest, self).__init__(
            '/regions/{regionId}/backupSynchronicities', 'POST', header, version)
        self.parameters = parameters


class CreateBackupSynchronicityParameters(object):

    def __init__(self, regionId, instanceId, srcRegion, dstRegion):
        """
        :param regionId: Region ID
        :param instanceId: 源实例ID
        :param srcRegion: 源实例所在地域
        :param dstRegion: 备份同步的目标地域
        """

        self.regionId = regionId
        self.instanceId = instanceId
        self.srcRegion = srcRegion
        self.dstRegion = dstRegion

