# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class DeviceSnapshotRequestVO(object):

    def __init__(self, deviceId, thingTypeName, params=None, deviceName=None):
        """
        :param deviceId:  设备标识ID
        :param params: (Optional) 参数名称列表
        :param deviceName: (Optional) 设备名称
        :param thingTypeName:  物类型名称
        """

        self.deviceId = deviceId
        self.params = params
        self.deviceName = deviceName
        self.thingTypeName = thingTypeName
