# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DescribeConsumerGroupsRequest(JDCloudRequest):
    """
    consumerGroup列表
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DescribeConsumerGroupsRequest, self).__init__(
            '/regions/{regionId}/instances/{instanceId}/consumerGroups', 'GET', header, version)
        self.parameters = parameters


class DescribeConsumerGroupsParameters(object):

    def __init__(self,regionId, instanceId, pageSize, pageNumber):
        """
        :param regionId: 区域ID
        :param instanceId: 实例id
        :param pageSize: 分页大小
        :param pageNumber: 页码
        """

        self.regionId = regionId
        self.instanceId = instanceId
        self.consumerFilter = None
        self.pageSize = pageSize
        self.pageNumber = pageNumber

    def setConsumerFilter(self, consumerFilter):
        """
        :param consumerFilter: (Optional) consumerGroup的过滤条件
        """
        self.consumerFilter = consumerFilter

