# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class IpResourceFlow(object):

    def __init__(self, time=None, postProtect=None, preProtect=None, unit=None):
        """
        :param time: (Optional) 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ
        :param postProtect: (Optional) 防护后流量
        :param preProtect: (Optional) 防护前流量
        :param unit: (Optional) 流量单位
        """

        self.time = time
        self.postProtect = postProtect
        self.preProtect = preProtect
        self.unit = unit
