# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class PortSet(object):

    def __init__(self, id=None, name=None, port=None, remark=None):
        """
        :param id: (Optional) 端口库 Id
        :param name: (Optional) 端口库名称
        :param port: (Optional) 端口或端口范围的数组
        :param remark: (Optional) 备注
        """

        self.id = id
        self.name = name
        self.port = port
        self.remark = remark
