# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class OrderResponseObject(object):

    def __init__(self, actualFee=None, appCode=None, appName=None, chargeMode=None, createTime=None, discountFee=None, orderNumber=None, orderType=None, payTime=None, payType=None, paymentNumber=None, pin=None, selfSupportType=None, serviceName=None, status=None, totalFee=None):
        """
        :param actualFee: (Optional) 订单应付金额
        :param appCode: (Optional) 业务线
        :param appName: (Optional) 业务名称
        :param chargeMode: (Optional) 计费类型(CONFIG-按配置,FLOW-按用量MONTHLY-包年包月,ONCE-按次付费)
        :param createTime: (Optional) 订单创建时间（格式：yyyy-MM-dd HH:mm:ss）
        :param discountFee: (Optional) 折扣金额
        :param orderNumber: (Optional) 订单号
        :param orderType: (Optional) 购买订单类型(NEW-新购,RENEW-续费，RESIZE_FORMULA-配置变更)
        :param payTime: (Optional) 订单支付时间（格式：yyyy-MM-dd HH:mm:ss）
        :param payType: (Optional) 付费类型(PRE_PAID-预付费,POST_PAID-后付费)
        :param paymentNumber: (Optional) 订单号
        :param pin: (Optional) 用户pin
        :param selfSupportType: (Optional) 自营类型(SELF_SUPPORT-自营,THIRD_PARTY_SUPPORT-非自营)
        :param serviceName: (Optional) 产品线名称
        :param status: (Optional) 订单状态（PAID-已支付,FAILED-失败,NO_PAY-未支付,DEALING-处理中,CANCELED-已取消,REFUND_PART-部分退款,REFUND_ALL-全部退款）
        :param totalFee: (Optional) 订单总金额
        """

        self.actualFee = actualFee
        self.appCode = appCode
        self.appName = appName
        self.chargeMode = chargeMode
        self.createTime = createTime
        self.discountFee = discountFee
        self.orderNumber = orderNumber
        self.orderType = orderType
        self.payTime = payTime
        self.payType = payType
        self.paymentNumber = paymentNumber
        self.pin = pin
        self.selfSupportType = selfSupportType
        self.serviceName = serviceName
        self.status = status
        self.totalFee = totalFee
