# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class VserverGroupBackendServer(object):

    def __init__(self, serverId=None, port=None, weight=None):
        """
        :param serverId: (Optional) 负载均衡实例ID。
        :param port: (Optional) 后端服务器端口。
        :param weight: (Optional) 后端服务器的权重。
        """

        self.serverId = serverId
        self.port = port
        self.weight = weight
