# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class CreateOfflineAnalysisTaskRequest(JDCloudRequest):
    """
    创建redis实例离线数据分析任务
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(CreateOfflineAnalysisTaskRequest, self).__init__(
            '/regions/{regionId}/cacheInstance/{cacheInstanceId}/createOfflineAnalysisTask', 'POST', header, version)
        self.parameters = parameters


class CreateOfflineAnalysisTaskParameters(object):

    def __init__(self,regionId, cacheInstanceId, ):
        """
        :param regionId: 缓存Redis实例所在区域的Region ID。目前有华北-北京、华南-广州、华东-上海三个区域，Region ID分别为cn-north-1、cn-south-1、cn-east-2
        :param cacheInstanceId: 缓存Redis实例ID，是访问实例的唯一标识
        """

        self.regionId = regionId
        self.cacheInstanceId = cacheInstanceId
        self.backupIds = None
        self.prefixSeparator = None
        self.keyPrefix = None
        self.top = None

    def setBackupIds(self, backupIds):
        """
        :param backupIds: (Optional) 选择的历史备份文件，如果没有，表示新建备份，对所有分片进行分析
        """
        self.backupIds = backupIds

    def setPrefixSeparator(self, prefixSeparator):
        """
        :param prefixSeparator: (Optional) Key前缀分隔符，和keyPrefix同时只能有一个
        """
        self.prefixSeparator = prefixSeparator

    def setKeyPrefix(self, keyPrefix):
        """
        :param keyPrefix: (Optional) 要统计的key前缀，和prefixSeparator同时只能有一个
        """
        self.keyPrefix = keyPrefix

    def setTop(self, top):
        """
        :param top: (Optional) 获取top大key
        """
        self.top = top

