# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class UserGetDiagnoseReportRequest(JDCloudRequest):
    """
    获取指定诊断任务的详细报告，包括基本信息、诊断摘要、性能信息和慢日志
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(UserGetDiagnoseReportRequest, self).__init__(
            '/diagnoseReport', 'GET', header, version)
        self.parameters = parameters


class UserGetDiagnoseReportParameters(object):

    def __init__(self,taskId):
        """
        :param taskId: 诊断任务ID
        """

        self.taskId = taskId

