# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class CertDescDetail(object):

    def __init__(self, certId=None, certName=None, commonName=None, certType=None, issuer=None, startTime=None, endTime=None, dnsNames=None, digest=None, totalCount=None, usedBy=None):
        """
        :param certId: (Optional) 证书Id
        :param certName: (Optional) 证书名称
        :param commonName: (Optional) 绑定域名
        :param certType: (Optional) 证书类型
        :param issuer: (Optional) 签发者
        :param startTime: (Optional) 开始时间
        :param endTime: (Optional) 结束时间
        :param dnsNames: (Optional) 域名
        :param digest: (Optional) 对私钥文件使用sha256算法计算的摘要信息
        :param totalCount: (Optional) 绑定信息的总数量
        :param usedBy: (Optional) 证书关联信息
        """

        self.certId = certId
        self.certName = certName
        self.commonName = commonName
        self.certType = certType
        self.issuer = issuer
        self.startTime = startTime
        self.endTime = endTime
        self.dnsNames = dnsNames
        self.digest = digest
        self.totalCount = totalCount
        self.usedBy = usedBy
