# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AvailableRegion(object):

    def __init__(self, regionId=None, regionName=None, soldOut=None, quota=None, availableZones=None):
        """
        :param regionId: (Optional) 地域id
        :param regionName: (Optional) 地域名
        :param soldOut: (Optional) 是否售罄
        :param quota: (Optional) 用户配额
        :param availableZones: (Optional) 可用区列表
        """

        self.regionId = regionId
        self.regionName = regionName
        self.soldOut = soldOut
        self.quota = quota
        self.availableZones = availableZones
