# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class SentinelCluster(object):

    def __init__(self, name=None, namespace=None, azList=None, chartVersion=None, clusterId=None):
        """
        :param name: (Optional) 哨兵集群名称
        :param namespace: (Optional) 哨兵集群所在命名空间
        :param azList: (Optional) 哨兵集群所在可用区列表
        :param chartVersion: (Optional) sentinel集群的Chart版本
        :param clusterId: (Optional) sentinel集群所在集群ID
        """

        self.name = name
        self.namespace = namespace
        self.azList = azList
        self.chartVersion = chartVersion
        self.clusterId = clusterId
