# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ClusterDetailModel(object):

    def __init__(self, id=None, name=None, clusterPrimaryId=None, status=None, nodeCount=None, payType=None, payPrice=None, createTime=None, duration=None, hardware=None, softwareStack=None, dataCenter=None, jssFlag=None, haFlag=None, vpcName=None, vpcSubnetName=None, bandwidthOut=None):
        """
        :param id: (Optional) 集群ID
        :param name: (Optional) 集群名称，长度为6到32个字符，支持中文、数字、大小写字母、英文下划线“_”及中划线“-”
        :param clusterPrimaryId: (Optional) 集群主键ID
        :param status: (Optional) 集群状态
        :param nodeCount: (Optional) 节点数量
        :param payType: (Optional) 付费类型
        :param payPrice: (Optional) 付费价格
        :param createTime: (Optional) 创建时间
        :param duration: (Optional) 运营时长
        :param hardware: (Optional) 
        :param softwareStack: (Optional) 软件信息
        :param dataCenter: (Optional) 地域，同regionID
        :param jssFlag: (Optional) 是否关联对象存储
        :param haFlag: (Optional) 是否为高可用模式
        :param vpcName: (Optional) 私有网络名称
        :param vpcSubnetName: (Optional) 子网名称
        :param bandwidthOut: (Optional) 网络带宽
        """

        self.id = id
        self.name = name
        self.clusterPrimaryId = clusterPrimaryId
        self.status = status
        self.nodeCount = nodeCount
        self.payType = payType
        self.payPrice = payPrice
        self.createTime = createTime
        self.duration = duration
        self.hardware = hardware
        self.softwareStack = softwareStack
        self.dataCenter = dataCenter
        self.jssFlag = jssFlag
        self.haFlag = haFlag
        self.vpcName = vpcName
        self.vpcSubnetName = vpcSubnetName
        self.bandwidthOut = bandwidthOut
