# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class DataLoadHistory(object):

    def __init__(self, id, fileName, projectCode, tableName, applicationId, state, stateDesc, createdDate, ):
        """
        :param id:  主键ID
        :param fileName:  文件名称
        :param projectCode:  项目编码
        :param tableName:  目标表名
        :param applicationId:  任务id
        :param state:  任务状态
        :param stateDesc:  任务状态描述
        :param createdDate:  创建时间
        """

        self.id = id
        self.fileName = fileName
        self.projectCode = projectCode
        self.tableName = tableName
        self.applicationId = applicationId
        self.state = state
        self.stateDesc = stateDesc
        self.createdDate = createdDate
