# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class GpdjmcCalcJobDTO(object):

    def __init__(self, projectId=None, projectName=None, projectNameMatch=None, nameKeyWord=None, relationType=None, modelId=None, modelName=None, modelNameMatch=None, gitUrl=None, tableId=None, databaseName=None, marketId=None, marketCode=None, marketName=None, redirectType=None, tableName=None, tableNameMatch=None, jobName=None, jobSystem=None, triggerType=None, triggerConfig=None, zipCommand=None, zipFileName=None, zipParams=None, dependencies=None, manager=None, cooperator=None, priority=None, jobDesc=None, scriptType=None, runScript=None, scriptContent=None, cycle=None, sequence=None, lifeCycle=None, retry=None, retryCount=None, retryInterval=None, notifyOccasion=None, notifyTime=None, notifyPattern=None, notifier=None, startRunTime=None, endRunTime=None, runTime=None, runDate=None, flowId=None, taskId=None, userAccount=None, userPwd=None, markIds=None, runTimeOut=None, scriptSourceType=None, scriptTemplate=None, dmrTableIds=None, dmrTables=None, gitFilesList=None, isDeploy=None, scriptPath=None, scriptByte=None, fileId=None, publishDesc=None, scriptInfo=None, version=None, channel=None, sequenceStartTime=None, sequenceEndTime=None, sequenceInterval=None, runParams=None, runQueue=None, sparkJarRunParams=None, submitConf=None, jobStatus=None, resourceCode=None, workspaceCode=None, cstJobName=None, fromGravity=None, processType=None, companyCode=None, windowStartTime=None, windowEndTime=None, scriptUrl=None, resourceName=None, datasourceId=None, inputParams=None, outputParams=None, loopParam=None):
        """
        :param projectId: (Optional) 
        :param projectName: (Optional) 
        :param projectNameMatch: (Optional) 
        :param nameKeyWord: (Optional) 
        :param relationType: (Optional) 
        :param modelId: (Optional) 
        :param modelName: (Optional) 
        :param modelNameMatch: (Optional) 
        :param gitUrl: (Optional) 
        :param tableId: (Optional) 
        :param databaseName: (Optional) 
        :param marketId: (Optional) 
        :param marketCode: (Optional) 
        :param marketName: (Optional) 
        :param redirectType: (Optional) 
        :param tableName: (Optional) 
        :param tableNameMatch: (Optional) 
        :param jobName: (Optional) 
        :param jobSystem: (Optional) 
        :param triggerType: (Optional) 
        :param triggerConfig: (Optional) 
        :param zipCommand: (Optional) 
        :param zipFileName: (Optional) 
        :param zipParams: (Optional) 
        :param dependencies: (Optional) 
        :param manager: (Optional) 
        :param cooperator: (Optional) 
        :param priority: (Optional) 优先级，l1 - l4
        :param jobDesc: (Optional) 
        :param scriptType: (Optional) 
        :param runScript: (Optional) 
        :param scriptContent: (Optional) 
        :param cycle: (Optional) 
        :param sequence: (Optional) 
        :param lifeCycle: (Optional) 
        :param retry: (Optional) 
        :param retryCount: (Optional) 
        :param retryInterval: (Optional) 
        :param notifyOccasion: (Optional) 
        :param notifyTime: (Optional) 
        :param notifyPattern: (Optional) 
        :param notifier: (Optional) 
        :param startRunTime: (Optional) 
        :param endRunTime: (Optional) 
        :param runTime: (Optional) 
        :param runDate: (Optional) 
        :param flowId: (Optional) 
        :param taskId: (Optional) 
        :param userAccount: (Optional) 
        :param userPwd: (Optional) 
        :param markIds: (Optional) 
        :param runTimeOut: (Optional) 
        :param scriptSourceType: (Optional) 
        :param scriptTemplate: (Optional) 
        :param dmrTableIds: (Optional) 
        :param dmrTables: (Optional) 
        :param gitFilesList: (Optional) 
        :param isDeploy: (Optional) 
        :param scriptPath: (Optional) 
        :param scriptByte: (Optional) 
        :param fileId: (Optional) 
        :param publishDesc: (Optional) 
        :param scriptInfo: (Optional) 
        :param version: (Optional) 
        :param channel: (Optional) 
        :param sequenceStartTime: (Optional) 
        :param sequenceEndTime: (Optional) 
        :param sequenceInterval: (Optional) 
        :param runParams: (Optional) 
        :param runQueue: (Optional) 
        :param sparkJarRunParams: (Optional) 
        :param submitConf: (Optional) 
        :param jobStatus: (Optional) 
        :param resourceCode: (Optional) 计算资源组code
        :param workspaceCode: (Optional) 工作空间code
        :param cstJobName: (Optional) 客户作业名称
        :param fromGravity: (Optional) 
        :param processType: (Optional) 处理类型
        :param companyCode: (Optional) 租户code
        :param windowStartTime: (Optional) 窗口期开始时间
        :param windowEndTime: (Optional) 窗口期结束时间
        :param scriptUrl: (Optional) 脚本存储路径
        :param resourceName: (Optional) 计算资源组名称
        :param datasourceId: (Optional) 数据源ID，在一些要访问外部源的任务中，需要指定该数据源ID
        :param inputParams: (Optional) 输入参数列表
        :param outputParams: (Optional) 输出参数列表
        :param loopParam: (Optional) 循环任务参数
        """

        self.projectId = projectId
        self.projectName = projectName
        self.projectNameMatch = projectNameMatch
        self.nameKeyWord = nameKeyWord
        self.relationType = relationType
        self.modelId = modelId
        self.modelName = modelName
        self.modelNameMatch = modelNameMatch
        self.gitUrl = gitUrl
        self.tableId = tableId
        self.databaseName = databaseName
        self.marketId = marketId
        self.marketCode = marketCode
        self.marketName = marketName
        self.redirectType = redirectType
        self.tableName = tableName
        self.tableNameMatch = tableNameMatch
        self.jobName = jobName
        self.jobSystem = jobSystem
        self.triggerType = triggerType
        self.triggerConfig = triggerConfig
        self.zipCommand = zipCommand
        self.zipFileName = zipFileName
        self.zipParams = zipParams
        self.dependencies = dependencies
        self.manager = manager
        self.cooperator = cooperator
        self.priority = priority
        self.jobDesc = jobDesc
        self.scriptType = scriptType
        self.runScript = runScript
        self.scriptContent = scriptContent
        self.cycle = cycle
        self.sequence = sequence
        self.lifeCycle = lifeCycle
        self.retry = retry
        self.retryCount = retryCount
        self.retryInterval = retryInterval
        self.notifyOccasion = notifyOccasion
        self.notifyTime = notifyTime
        self.notifyPattern = notifyPattern
        self.notifier = notifier
        self.startRunTime = startRunTime
        self.endRunTime = endRunTime
        self.runTime = runTime
        self.runDate = runDate
        self.flowId = flowId
        self.taskId = taskId
        self.userAccount = userAccount
        self.userPwd = userPwd
        self.markIds = markIds
        self.runTimeOut = runTimeOut
        self.scriptSourceType = scriptSourceType
        self.scriptTemplate = scriptTemplate
        self.dmrTableIds = dmrTableIds
        self.dmrTables = dmrTables
        self.gitFilesList = gitFilesList
        self.isDeploy = isDeploy
        self.scriptPath = scriptPath
        self.scriptByte = scriptByte
        self.fileId = fileId
        self.publishDesc = publishDesc
        self.scriptInfo = scriptInfo
        self.version = version
        self.channel = channel
        self.sequenceStartTime = sequenceStartTime
        self.sequenceEndTime = sequenceEndTime
        self.sequenceInterval = sequenceInterval
        self.runParams = runParams
        self.runQueue = runQueue
        self.sparkJarRunParams = sparkJarRunParams
        self.submitConf = submitConf
        self.jobStatus = jobStatus
        self.resourceCode = resourceCode
        self.workspaceCode = workspaceCode
        self.cstJobName = cstJobName
        self.fromGravity = fromGravity
        self.processType = processType
        self.companyCode = companyCode
        self.windowStartTime = windowStartTime
        self.windowEndTime = windowEndTime
        self.scriptUrl = scriptUrl
        self.resourceName = resourceName
        self.datasourceId = datasourceId
        self.inputParams = inputParams
        self.outputParams = outputParams
        self.loopParam = loopParam
