# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class GpmnJobSpendTimeRankingVo(object):

    def __init__(self, order=None, jobName=None, jobType=None, manager=None, spendTimeAvg=None, spendTimeLongest=None, cstJobName=None):
        """
        :param order: (Optional) 排名
        :param jobName: (Optional) 作业名
        :param jobType: (Optional) 作业类型描述
        :param manager: (Optional) 负责人
        :param spendTimeAvg: (Optional) 平均运行时长，形如hh:mm:ss
        :param spendTimeLongest: (Optional) 运行最大时长，形如 hh:mm:ss
        :param cstJobName: (Optional) 客户作业名
        """

        self.order = order
        self.jobName = jobName
        self.jobType = jobType
        self.manager = manager
        self.spendTimeAvg = spendTimeAvg
        self.spendTimeLongest = spendTimeLongest
        self.cstJobName = cstJobName
