# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class JcwSpaceSummaryVo(object):

    def __init__(self, incrementalUsedByDay=None, totalUsed=None, totalFree=None, usedPercent=None, collectTime=None):
        """
        :param incrementalUsedByDay: (Optional) 集群每日存储空间增量
        :param totalUsed: (Optional) 总使用量
        :param totalFree: (Optional) 总剩余空间
        :param usedPercent: (Optional) 使用率
        :param collectTime: (Optional) 采集时间
        """

        self.incrementalUsedByDay = incrementalUsedByDay
        self.totalUsed = totalUsed
        self.totalFree = totalFree
        self.usedPercent = usedPercent
        self.collectTime = collectTime
