# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TaskRepublishReq(object):

    def __init__(self, historyId=None, pin=None, taskDraftId=None, reason=None, enable=None):
        """
        :param historyId: (Optional) 任务发布历史id
        :param pin: (Optional) 操作用户
        :param taskDraftId: (Optional) 任务的草稿id
        :param reason: (Optional) 发布原因
        :param enable: (Optional) 是否启用任务, TASK节点传true； INTERNAL_TASK工作流最后一个节点传true，其他传false；WORKFLOW传false
        """

        self.historyId = historyId
        self.pin = pin
        self.taskDraftId = taskDraftId
        self.reason = reason
        self.enable = enable
