# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TaskFullTextQueryRes(object):

    def __init__(self, taskDraftId=None, taskName=None, taskType=None, nodeIcon=None, manager=None, catalog=None, createTime=None, updateTime=None, score=None, lines=None):
        """
        :param taskDraftId: (Optional) 任务草稿ID，例如：tsk_123
        :param taskName: (Optional) 任务名称
        :param taskType: (Optional) 任务类型
        :param nodeIcon: (Optional) 任务类型图标
        :param manager: (Optional) 任务负责人
        :param catalog: (Optional) 任务所属业务路径
        :param createTime: (Optional) 任务创建时间
        :param updateTime: (Optional) 任务更新时间
        :param score: (Optional) 相关度得分
        :param lines: (Optional) 检索结果的行
        """

        self.taskDraftId = taskDraftId
        self.taskName = taskName
        self.taskType = taskType
        self.nodeIcon = nodeIcon
        self.manager = manager
        self.catalog = catalog
        self.createTime = createTime
        self.updateTime = updateTime
        self.score = score
        self.lines = lines
