# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TaskDebugHistoryRes(object):

    def __init__(self, debugId=None, startTime=None, endTime=None, status=None, filePath=None, scriptContent=None, execMode=None, args=None, execEngine=None, operator=None, resultPath=None, loopInfo=None, datasourceInfo=None, resourceCode=None, resourceName=None, applicationId=None, sparkJarInfo=None, runInfo=None):
        """
        :param debugId: (Optional) 运行 ID
        :param startTime: (Optional) 开始时间
        :param endTime: (Optional) 结束时间
        :param status: (Optional) 状态，WAITING_EXEC：等待执行，RUNNING：执行中，SUCCESS：成功，FAILURE：失败， CANCELLED：中止，TIMEOUT：超时
        :param filePath: (Optional) 文件路径
        :param scriptContent: (Optional) 脚本内容
        :param execMode: (Optional) 执行方式 0：全文执行， 1：选中执行
        :param args: (Optional) 运行参数
        :param execEngine: (Optional) 执行引擎
        :param operator: (Optional) 操作人
        :param resultPath: (Optional) 结果路径
        :param loopInfo: (Optional) 循环节点信息
        :param datasourceInfo: (Optional) 数据源配置信息
        :param resourceCode: (Optional) 资源组 code
        :param resourceName: (Optional) 资源组名称
        :param applicationId: (Optional) 运行时的 applicationId
        :param sparkJarInfo: (Optional) spark 任务配置信息
        :param runInfo: (Optional) 运行参数信息
        """

        self.debugId = debugId
        self.startTime = startTime
        self.endTime = endTime
        self.status = status
        self.filePath = filePath
        self.scriptContent = scriptContent
        self.execMode = execMode
        self.args = args
        self.execEngine = execEngine
        self.operator = operator
        self.resultPath = resultPath
        self.loopInfo = loopInfo
        self.datasourceInfo = datasourceInfo
        self.resourceCode = resourceCode
        self.resourceName = resourceName
        self.applicationId = applicationId
        self.sparkJarInfo = sparkJarInfo
        self.runInfo = runInfo
