# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AgentPlan(object):

    def __init__(self, id=None, backupType=None, schedule=None, datasource=None, databases=None, tables=None, useBinlog=None):
        """
        :param id: (Optional) 
        :param backupType: (Optional) 备份方式
        :param schedule: (Optional) 
        :param datasource: (Optional) 
        :param databases: (Optional) 
        :param tables: (Optional) 
        :param useBinlog: (Optional) 
        """

        self.id = id
        self.backupType = backupType
        self.schedule = schedule
        self.datasource = datasource
        self.databases = databases
        self.tables = tables
        self.useBinlog = useBinlog
