# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class CreateBackupRequest(JDCloudRequest):
    """
    创建备份</br>- SQL Server：支持</br>- MySQL：暂不支持
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(CreateBackupRequest, self).__init__(
            '/regions/{regionId}/backups', 'POST', header, version)
        self.parameters = parameters


class CreateBackupParameters(object):

    def __init__(self, regionId, ):
        """
        :param regionId: 地域代码
        """

        self.regionId = regionId
        self.instanceId = None
        self.backupSpec = None

    def setInstanceId(self, instanceId):
        """
        :param instanceId: (Optional) 集群ID
        """
        self.instanceId = instanceId

    def setBackupSpec(self, backupSpec):
        """
        :param backupSpec: (Optional) 备份规格
        """
        self.backupSpec = backupSpec

