# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class CollectConf(object):

    def __init__(self, collectTemplateUID=None, collectType=None, destination=None, extSpec=None, file=None, filters=None, logtopicUID=None, path=None, pin=None, readFromHead=None, regexpStr=None, agentMeta=None):
        """
        :param collectTemplateUID: (Optional) collectTemplateUID
        :param collectType: (Optional) 采集配置类型, 默认为vm，可支持binlog
        :param destination: (Optional) 
        :param extSpec: (Optional) other Spec
        :param file: (Optional) 采集文件名称，支持通配
        :param filters: (Optional) filters 过滤器V1：多个词之间为or的关系
        :param logtopicUID: (Optional) logtopicUID 日志主题UID
        :param path: (Optional) 采集文件路径，支持通配
        :param pin: (Optional) 用户 PIN
        :param readFromHead: (Optional) 是否开启从头采集
        :param regexpStr: (Optional) 首行正则表达式
        :param agentMeta: (Optional) agent元信息
        """

        self.collectTemplateUID = collectTemplateUID
        self.collectType = collectType
        self.destination = destination
        self.extSpec = extSpec
        self.file = file
        self.filters = filters
        self.logtopicUID = logtopicUID
        self.path = path
        self.pin = pin
        self.readFromHead = readFromHead
        self.regexpStr = regexpStr
        self.agentMeta = agentMeta
