# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class FirewallRule(object):

    def __init__(self, products=None, priority=None, paused=None, ref=None, action_parameters=None, action=None, filter=None, id=None, description=None):
        """
        :param products: (Optional) 
        :param priority: (Optional) 规则的优先级，允许控制处理顺序。一个较小的数字表示高优先级。如果不提供，任何有优先权的规则将在没有优先权的规则之前排序。
        :param paused: (Optional) 此防火墙规则当前是否已暂停。
        :param ref: (Optional) 短引用标记，用于快速选择相关规则。
        :param action_parameters: (Optional) 
        :param action: (Optional) 对匹配到的请求采取的措施。有效值：js_challenge/block/challenge/allow/bypass
js_challenge表示Js挑战
block表示阻止
challenge表示验证码
allow表示允许
bypass表示绕过

        :param filter: (Optional) 
        :param id: (Optional) 防火墙规则标识符
        :param description: (Optional) 对规则的描述，以帮助识别它。
        """

        self.products = products
        self.priority = priority
        self.paused = paused
        self.ref = ref
        self.action_parameters = action_parameters
        self.action = action
        self.filter = filter
        self.id = id
        self.description = description
