# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class OpZoneDetails(object):

    def __init__(self, zoneId=None, zoneName=None, zoneStatus=None, instanceId=None, instanceName=None, pin=None, packType=None, chargeState=None, icpStatus=None, zoneCreateTime=None, instanceExpireTime=None, pauseStatus=None, lockdownStatus=None, blackListEnable=None, whiteListEnable=None, totalFlowStr=None, usedFlowStr=None, remainingFlowStr=None, cnameSuffix=None, nameServers=None, verificationKey=None, zoneType=None, ipType=None):
        """
        :param zoneId: (Optional) 域名id
        :param zoneName: (Optional) 域名
        :param zoneStatus: (Optional) 域名状态：pending 待激活、active 已激活、remove 已删除
        :param instanceId: (Optional) 所属实例id
        :param instanceName: (Optional) 所属实例名称
        :param pin: (Optional) 所属PIN
        :param packType: (Optional) 套餐类型
        :param chargeState: (Optional) 计费状态
        :param icpStatus: (Optional) 备案状态：0 未备案、1 已备案
        :param zoneCreateTime: (Optional) 域名创建时间
        :param instanceExpireTime: (Optional) 实例到期时间
        :param pauseStatus: (Optional) Pause：0 未停服、1 已停服
        :param lockdownStatus: (Optional) LockDown：0 无、1 已配置lockdown
        :param blackListEnable: (Optional) 黑名单：0 未开启、1 已开启
        :param whiteListEnable: (Optional) 白名单：0 未开启、1 已开启
        :param totalFlowStr: (Optional) 套餐总流量
        :param usedFlowStr: (Optional) 套餐已使用流量
        :param remainingFlowStr: (Optional) 套餐剩余流量
        :param cnameSuffix: (Optional) CNAME后缀
        :param nameServers: (Optional) NS记录
        :param verificationKey: (Optional) TXT记录
        :param zoneType: (Optional) 接入方式 partial：半接入-CNAME full：全接入-NS
        :param ipType: (Optional) IP类型：0 共享 1 专用
        """

        self.zoneId = zoneId
        self.zoneName = zoneName
        self.zoneStatus = zoneStatus
        self.instanceId = instanceId
        self.instanceName = instanceName
        self.pin = pin
        self.packType = packType
        self.chargeState = chargeState
        self.icpStatus = icpStatus
        self.zoneCreateTime = zoneCreateTime
        self.instanceExpireTime = instanceExpireTime
        self.pauseStatus = pauseStatus
        self.lockdownStatus = lockdownStatus
        self.blackListEnable = blackListEnable
        self.whiteListEnable = whiteListEnable
        self.totalFlowStr = totalFlowStr
        self.usedFlowStr = usedFlowStr
        self.remainingFlowStr = remainingFlowStr
        self.cnameSuffix = cnameSuffix
        self.nameServers = nameServers
        self.verificationKey = verificationKey
        self.zoneType = zoneType
        self.ipType = ipType
