# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class OpZoneRecords(object):

    def __init__(self, recordId=None, zoneId=None, name=None, type=None, content=None, ttl=None, proxied=None, createTime=None, updateTime=None, proxiable=None, priority=None):
        """
        :param recordId: (Optional) 解析记录ID
        :param zoneId: (Optional) 域名id
        :param name: (Optional) 主机名
        :param type: (Optional) 记录类型
        :param content: (Optional) 记录值
        :param ttl: (Optional) TTL
        :param proxied: (Optional) 代理状态
        :param createTime: (Optional) 创建时间
        :param updateTime: (Optional) 更新时间
        :param proxiable: (Optional) 是否可代理
        :param priority: (Optional) 优先级
        """

        self.recordId = recordId
        self.zoneId = zoneId
        self.name = name
        self.type = type
        self.content = content
        self.ttl = ttl
        self.proxied = proxied
        self.createTime = createTime
        self.updateTime = updateTime
        self.proxiable = proxiable
        self.priority = priority
