# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class DescribeIdcInspection(object):

    def __init__(self, inspectionDate=None, idc=None, idcName=None, status=None):
        """
        :param inspectionDate: (Optional) 巡检日期
        :param idc: (Optional) 机房英文标识
        :param idcName: (Optional) 机房名称
        :param status: (Optional) 巡检状态
        """

        self.inspectionDate = inspectionDate
        self.idc = idc
        self.idcName = idcName
        self.status = status
