# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ResourceChange(object):

    def __init__(self, action=None, details=None, logicalResourceId=None, physicalResourceId=None, replacement=None, resourceType=None, scope=None):
        """
        :param action: (Optional) 
        :param details: (Optional) 更新操作中将对资源做的改变详情
        :param logicalResourceId: (Optional) 资源在模板中的逻辑id
        :param physicalResourceId: (Optional) 资源物理id
        :param replacement: (Optional) 
        :param resourceType: (Optional) 资源类型
        :param scope: (Optional) 更新操作中修改发生的位置
        """

        self.action = action
        self.details = details
        self.logicalResourceId = logicalResourceId
        self.physicalResourceId = physicalResourceId
        self.replacement = replacement
        self.resourceType = resourceType
        self.scope = scope
