# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ResourceTypes(object):

    def __init__(self, attributes=None, description=None, documentation=None, properties=None):
        """
        :param attributes: (Optional) 资源输出参数定义
        :param description: (Optional) 资源描述
        :param documentation: (Optional) 文档链接
        :param properties: (Optional) 资源属性定义
        """

        self.attributes = attributes
        self.description = description
        self.documentation = documentation
        self.properties = properties
