# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class AdminDescribeRunsCountRequest(JDCloudRequest):
    """
    查询 pin 下所有的资源，按微调运行状态统计数量。

管理员接口，用于快速了解当前账号下各状态的资源数量分布。

## 使用场景

- 资源概览监控
- 运行状态分布分析
- 资源使用统计

## 过滤条件

- `workspaceId`：工作空间ID，精确匹配
- `state`：运行状态，精确匹配，支持多个

    """

    def __init__(self, parameters, header=None, version="v1"):
        super(AdminDescribeRunsCountRequest, self).__init__(
            '/train/{regionId}/api/{apiType}/runs:count', 'GET', header, version)
        self.parameters = parameters


class AdminDescribeRunsCountParameters(object):

    def __init__(self,regionId, apiType, ):
        """
        :param regionId: 地域ID
        :param apiType: 接口类型(admin)
        """

        self.regionId = regionId
        self.apiType = apiType
        self.filters = None

    def setFilters(self, filters):
        """
        :param filters: (Optional) <b>filters 中支持使用以下关键字进行过滤</b>
`workspaceId`: 工作空间ID，精确匹配，支持单个。
`state`: 微调运行的状态，精确匹配，支持多个。

        """
        self.filters = filters

