# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class AdminDescribeJobListRequest(JDCloudRequest):
    """
    查询当前主账号下所有的训练任务列表。

管理员接口，可跨工作空间查询主账号下所有训练任务。

## 过滤条件

- `jobId`：任务ID，精确匹配，支持多个
- `permission`：权限类型，精确匹配
- `ownerUserPin`：所有者pin，精确匹配
- `ownerUser`：所有者名称，模糊匹配

    """

    def __init__(self, parameters, header=None, version="v1"):
        super(AdminDescribeJobListRequest, self).__init__(
            '/train/{regionId}/api/{apiType}/jobList', 'GET', header, version)
        self.parameters = parameters


class AdminDescribeJobListParameters(object):

    def __init__(self,regionId, apiType, ):
        """
        :param regionId: 地域ID
        :param apiType: 接口类型(admin)
        """

        self.regionId = regionId
        self.apiType = apiType
        self.pageNumber = None
        self.pageSize = None
        self.userTags = None
        self.resourceGroupIds = None
        self.filters = None

    def setPageNumber(self, pageNumber):
        """
        :param pageNumber: (Optional) 页码；默认为1。
        """
        self.pageNumber = pageNumber

    def setPageSize(self, pageSize):
        """
        :param pageSize: (Optional) 分页大小；默认为20；取值范围[1, 500]。
        """
        self.pageSize = pageSize

    def setUserTags(self, userTags):
        """
        :param userTags: (Optional) 用户自定义标签列表。
        """
        self.userTags = userTags

    def setResourceGroupIds(self, resourceGroupIds):
        """
        :param resourceGroupIds: (Optional) 资源组ID列表
        """
        self.resourceGroupIds = resourceGroupIds

    def setFilters(self, filters):
        """
        :param filters: (Optional) <b>filters 中支持使用以下关键字进行过滤</b>
`jobId`: 训练任务ID，精确匹配，支持多个。
`permission`: 权限，精确匹配，支持单个，可选(public,private)。
`ownerUserPin`: 所有者pin，精确匹配，支持多个。
`ownerUser`: 所有者名称，模糊匹配，支持单个。

        """
        self.filters = filters

