# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DescribeInstancesRequest(JDCloudRequest):
    """
    查询训练任务实例列表。

获取训练任务下所有运行实例（Pod）的详细信息，包括状态、IP、运行时长等。

## 使用场景

- 查看各实例的运行状态
- 获取实例终端访问地址
- 排查分布式训练中的节点问题

    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DescribeInstancesRequest, self).__init__(
            '/train/{regionId}/workspaces/{workspaceId}/jobs/{jobId}:instances', 'GET', header, version)
        self.parameters = parameters


class DescribeInstancesParameters(object):

    def __init__(self,regionId, workspaceId, jobId, ):
        """
        :param regionId: 地域ID
        :param workspaceId: 工作空间ID
        :param jobId: 训练任务ID
        """

        self.regionId = regionId
        self.workspaceId = workspaceId
        self.jobId = jobId
        self.pageNumber = None
        self.pageSize = None
        self.anomalyFirst = None
        self.filters = None

    def setPageNumber(self, pageNumber):
        """
        :param pageNumber: (Optional) 页码；默认为1。
        """
        self.pageNumber = pageNumber

    def setPageSize(self, pageSize):
        """
        :param pageSize: (Optional) 分页大小；默认为20；取值范围[1, 500]。
        """
        self.pageSize = pageSize

    def setAnomalyFirst(self, anomalyFirst):
        """
        :param anomalyFirst: (Optional) 异常状态数据优先展示；默认为false
        """
        self.anomalyFirst = anomalyFirst

    def setFilters(self, filters):
        """
        :param filters: (Optional) <b>filters 中支持使用以下关键字进行过滤</b>
`name`: 实例名称，模糊匹配，支持单个。
`type`: 实例类型，模糊匹配，支持单个。
`state`: 实例状态，精确匹配，支持多个，用","隔开。
`ip`: 实例Ip，精确匹配，支持多个，用","隔开。

        """
        self.filters = filters

