# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DescribeCodeRepoConfigsRequest(JDCloudRequest):
    """
    获取代码仓配置列表
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DescribeCodeRepoConfigsRequest, self).__init__(
            '/repo-regions/{regionId}/workspace/{workspaceId}/codeRepoConfig', 'GET', header, version)
        self.parameters = parameters


class DescribeCodeRepoConfigsParameters(object):

    def __init__(self,regionId, workspaceId, ):
        """
        :param regionId: 地域ID
        :param workspaceId: 工作空间ID
        """

        self.regionId = regionId
        self.workspaceId = workspaceId
        self.pageNumber = None
        self.pageSize = None
        self.filters = None

    def setPageNumber(self, pageNumber):
        """
        :param pageNumber: (Optional) 页码；默认为1。
        """
        self.pageNumber = pageNumber

    def setPageSize(self, pageSize):
        """
        :param pageSize: (Optional) 分页大小；<br>默认为10；取值范围[1, 100]。
        """
        self.pageSize = pageSize

    def setFilters(self, filters):
        """
        :param filters: (Optional) <b>filters 中支持使用以下关键字进行过滤</b>
`repoName`: 代码仓配置名称，模糊匹配，支持单个
`createUser`: 创建人名称，模糊匹配，支持单个
`repoType`: 代码库类型[github,coding]，精确匹配，支持多个
`repoId`: 代码仓ID，精确匹配，支持多个
`permission`: 权限，精确匹配，支持单个，可选(public,private)。
`ownerUser`: 所有者名称，模糊匹配，支持单个。
`ownerUserPin`: 所有者pin，精确匹配，支持多个。

        """
        self.filters = filters

