# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class UpdateLogpushJobRequest(JDCloudRequest):
    """
    更新日志推送作业
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(UpdateLogpushJobRequest, self).__init__(
            '/zones/{zone_identifier}/logpush$$jobs/{job_identifier}', 'PUT', header, version)
        self.parameters = parameters


class UpdateLogpushJobParameters(object):

    def __init__(self,zone_identifier, job_identifier, ):
        """
        :param zone_identifier: 
        :param job_identifier: 
        """

        self.zone_identifier = zone_identifier
        self.job_identifier = job_identifier
        self.enabled = None
        self.logpull_options = None
        self.destination_conf = None

    def setEnabled(self, enabled):
        """
        :param enabled: (Optional) 
        """
        self.enabled = enabled

    def setLogpull_options(self, logpull_options):
        """
        :param logpull_options: (Optional) 它指定了诸如请求的字段和时间戳格式之类的内容。例如：fields=fieldName1,fieldName2,fileNamek&timestamps=rfc3339&sample=0.1
        """
        self.logpull_options = logpull_options

    def setDestination_conf(self, destination_conf):
        """
        :param destination_conf: (Optional) 唯一标识数据推送目的地的字符串。可能包括目的地支持的其他参数。
        """
        self.destination_conf = destination_conf

