# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class GetFrontMetricValueResp(object):

    def __init__(self, dataType=None, timestamp=None, int32V=None, int64V=None, floatV=None, doubleV=None):
        """
        :param dataType: (Optional) 值类型，INT32/INT64/FLOAT
        :param timestamp: (Optional) 时间戳
        :param int32V: (Optional) int类型值
        :param int64V: (Optional) int64类型值
        :param floatV: (Optional) 浮点类型值
        :param doubleV: (Optional) 浮点类型值
        """

        self.dataType = dataType
        self.timestamp = timestamp
        self.int32V = int32V
        self.int64V = int64V
        self.floatV = floatV
        self.doubleV = doubleV
