# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class MetaColumnInfo(object):

    def __init__(self, fieldSort=None, fieldEnName=None, fieldCnName=None, fieldType=None, fieldLen=None, filedAccuracy=None, fieldChildType=None, defaultValue=None, ifAutoIncrement=None, ifNull=None, ifPrimaryKey=None, ifPartitionKey=None, ifDistributeKey=None, ifOrderKey=None, ifAggregateKey=None, aggregateFunction=None):
        """
        :param fieldSort: (Optional) 序号
        :param fieldEnName: (Optional) 字段英文名称
        :param fieldCnName: (Optional) 字段中文名称
        :param fieldType: (Optional) 字段类型
        :param fieldLen: (Optional) 字段长度 当字段类型为 bigdecimal 类型时配合字段精度一起使用
        :param filedAccuracy: (Optional) 字段精度
        :param fieldChildType: (Optional) 字段子类型
        :param defaultValue: (Optional) 字段默认值
        :param ifAutoIncrement: (Optional) 是否为自增列(y/n)，默认不是自增列
        :param ifNull: (Optional) 是否为空(y/n)
        :param ifPrimaryKey: (Optional) 是否为主键(y/n)
        :param ifPartitionKey: (Optional) 是否是分区字段(y/n)
        :param ifDistributeKey: (Optional) 是否是分桶键(y/n)
        :param ifOrderKey: (Optional) 是否是排序字段(y/n)
        :param ifAggregateKey: (Optional) 是否是聚合键(y/n)
        :param aggregateFunction: (Optional) 聚合函数
        """

        self.fieldSort = fieldSort
        self.fieldEnName = fieldEnName
        self.fieldCnName = fieldCnName
        self.fieldType = fieldType
        self.fieldLen = fieldLen
        self.filedAccuracy = filedAccuracy
        self.fieldChildType = fieldChildType
        self.defaultValue = defaultValue
        self.ifAutoIncrement = ifAutoIncrement
        self.ifNull = ifNull
        self.ifPrimaryKey = ifPrimaryKey
        self.ifPartitionKey = ifPartitionKey
        self.ifDistributeKey = ifDistributeKey
        self.ifOrderKey = ifOrderKey
        self.ifAggregateKey = ifAggregateKey
        self.aggregateFunction = aggregateFunction
