# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class MetaPartitionsCreate(object):

    def __init__(self, partitionName=None, values=None, valueStart=None, valueEnd=None):
        """
        :param partitionName: (Optional) 分区名称
        :param values: (Optional) 分区取值
        :param valueStart: (Optional) 分区值开始
        :param valueEnd: (Optional) 分区值结束
        """

        self.partitionName = partitionName
        self.values = values
        self.valueStart = valueStart
        self.valueEnd = valueEnd
