# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ProjectMetricDataReq(object):

    def __init__(self, orderBy=None, topk=None, bottomK=None, aggrType=None, downSampleType=None, startTime=None, endTime=None, timeInterval=None, tags=None, groupBy=None, rate=None, offset=None, serviceCode=None, dimension=None, resourceId=None, originalData=None, multiResources=None, filters=None):
        """
        :param orderBy: (Optional) orderBy
        :param topk: (Optional) topk
        :param bottomK: (Optional) bottomK
        :param aggrType: (Optional) aggrType
        :param downSampleType: (Optional) downSampleType
        :param startTime: (Optional) startTime
        :param endTime: (Optional) endTime
        :param timeInterval: (Optional) timeInterval
        :param tags: (Optional) tagFilter
        :param groupBy: (Optional) groupBy
        :param rate: (Optional) rate
        :param offset: (Optional) offset
        :param serviceCode: (Optional) serviceCode
        :param dimension: (Optional) dimension
        :param resourceId: (Optional) resourceId
        :param originalData: (Optional) originalData
        :param multiResources: (Optional) multiResources
        :param filters: (Optional) tagFilter
        """

        self.orderBy = orderBy
        self.topk = topk
        self.bottomK = bottomK
        self.aggrType = aggrType
        self.downSampleType = downSampleType
        self.startTime = startTime
        self.endTime = endTime
        self.timeInterval = timeInterval
        self.tags = tags
        self.groupBy = groupBy
        self.rate = rate
        self.offset = offset
        self.serviceCode = serviceCode
        self.dimension = dimension
        self.resourceId = resourceId
        self.originalData = originalData
        self.multiResources = multiResources
        self.filters = filters
