# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ProjectAlarmRulesRes(object):

    def __init__(self, projectCode=None, rulesCode=None, alarmName=None, alarmEnable=None, metricName=None, isCustomMetric=None, metric=None, metricRole=None, timeSpan=None, timeUnit=None, functions=None, operator=None, threshold=None, cycles=None, level=None, ifEmail=None, ifMessage=None, ifPhone=None, ifRobot=None, contacts=None, sendFrequency=None, ifAllDay=None, startTime=None, stopTime=None):
        """
        :param projectCode: (Optional) 实例code
        :param rulesCode: (Optional) 规则code
        :param alarmName: (Optional) 规则名称
        :param alarmEnable: (Optional) 是否启用
        :param metricName: (Optional) 监控项名称
        :param isCustomMetric: (Optional) 是否自定义监控项
        :param metric: (Optional) 监控项
        :param metricRole: (Optional) 指标类型 FE/BE/CN/QUEUE/PROJECT
        :param timeSpan: (Optional) 时间间隔
        :param timeUnit: (Optional) 时间单位
        :param functions: (Optional) 取值函数
        :param operator: (Optional) 运算符
        :param threshold: (Optional) 阈值
        :param cycles: (Optional) 周期
        :param level: (Optional) 告警级别，一般-General,严重-serious,紧急-emergency;
        :param ifEmail: (Optional) 是否发送邮件
        :param ifMessage: (Optional) 是否发送短信
        :param ifPhone: (Optional) 是否电话
        :param ifRobot: (Optional) 是否机器人（可支持钉钉、飞书、企业微信）
        :param contacts: (Optional) 联系人
        :param sendFrequency: (Optional) 通知频率. EVERYTIME-每次都进行告警通知,THIRTYMINUTES-每30分钟告警通知一次,ONEHOUR-每1小时告警通知一次,TWOHOUR-每2小时告警通知一次,SIXHOUR-每6小时告警通知一次;
        :param ifAllDay: (Optional) 是否全天
        :param startTime: (Optional) 创建时间
        :param stopTime: (Optional) 创建时间
        """

        self.projectCode = projectCode
        self.rulesCode = rulesCode
        self.alarmName = alarmName
        self.alarmEnable = alarmEnable
        self.metricName = metricName
        self.isCustomMetric = isCustomMetric
        self.metric = metric
        self.metricRole = metricRole
        self.timeSpan = timeSpan
        self.timeUnit = timeUnit
        self.functions = functions
        self.operator = operator
        self.threshold = threshold
        self.cycles = cycles
        self.level = level
        self.ifEmail = ifEmail
        self.ifMessage = ifMessage
        self.ifPhone = ifPhone
        self.ifRobot = ifRobot
        self.contacts = contacts
        self.sendFrequency = sendFrequency
        self.ifAllDay = ifAllDay
        self.startTime = startTime
        self.stopTime = stopTime
