# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ProjectAlarmRulesListReq(object):

    def __init__(self, projectCode=None, alarmName=None, metric=None, createTimeStart=None, createTimeEnd=None):
        """
        :param projectCode: (Optional) 实例code
        :param alarmName: (Optional) 告警名称
        :param metric: (Optional) 监控项
        :param createTimeStart: (Optional) 创建时间起点
        :param createTimeEnd: (Optional) 创建时间终点
        """

        self.projectCode = projectCode
        self.alarmName = alarmName
        self.metric = metric
        self.createTimeStart = createTimeStart
        self.createTimeEnd = createTimeEnd
