# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class UserDBPrivilegeResp(object):

    def __init__(self, id=None, projectCode=None, catalogName=None, database=None, metaDBPrivilegeType=None, authorizeUserName=None, createTime=None):
        """
        :param id: (Optional) id
        :param projectCode: (Optional) 项目ID
        :param catalogName: (Optional) Catalog名称
        :param database: (Optional) 库名称
        :param metaDBPrivilegeType: (Optional) 库权限类型
        :param authorizeUserName: (Optional) 授权人
        :param createTime: (Optional) 授权时间
        """

        self.id = id
        self.projectCode = projectCode
        self.catalogName = catalogName
        self.database = database
        self.metaDBPrivilegeType = metaDBPrivilegeType
        self.authorizeUserName = authorizeUserName
        self.createTime = createTime
