# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ReportInfo(object):

    def __init__(self, reportId=None, taskId=None, reportContent=None, execTime=None, reportState=None, completeTime=None, startTime=None, endTime=None):
        """
        :param reportId: (Optional) 报表ID
        :param taskId: (Optional) 任务ID
        :param reportContent: (Optional) 任务报表(base64,pdf)
        :param execTime: (Optional) 任务执行时间
        :param reportState: (Optional) 任务执行状态(0 执行中 1 成功)
        :param completeTime: (Optional) 任务完成时间
        :param startTime: (Optional) 报表统计开始时间
        :param endTime: (Optional) 报表统计结束时间
        """

        self.reportId = reportId
        self.taskId = taskId
        self.reportContent = reportContent
        self.execTime = execTime
        self.reportState = reportState
        self.completeTime = completeTime
        self.startTime = startTime
        self.endTime = endTime
