# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class TextResultsV2Request(JDCloudRequest):
    """
    查看文本疑似结果，小于10s/20次，请求频率过快服务器会拒绝处理
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(TextResultsV2Request, self).__init__(
            '/text:resultsv2', 'POST', header, version)
        self.parameters = parameters


class TextResultsV2Parameters(object):

    def __init__(self, ):
        """
        """

        self.bizType = None
        self.version = None

    def setBizType(self, bizType):
        """
        :param bizType: (Optional) 业务bizType，请联系客户经理获取
        """
        self.bizType = bizType

    def setVersion(self, version):
        """
        :param version: (Optional) 接口版本v4
        """
        self.version = version

