# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class CardBindStatusResp(object):

    def __init__(self, result=None, errorCode=None, errorDes=None, sepTime=None):
        """
        :param result: (Optional) 查询结果
        :param errorCode: (Optional) 错误码
        :param errorDes: (Optional) 错误描述
        :param sepTime: (Optional) 最近一次的分离时间
        """

        self.result = result
        self.errorCode = errorCode
        self.errorDes = errorDes
        self.sepTime = sepTime
