# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class BandwidthLimit(object):

    def __init__(self, productCode=None, chargeMode=None, chargeType=None, minBandwidth=None, maxBandwidth=None):
        """
        :param productCode: (Optional) EIP（弹性公网ip）、BWP（共享带宽包）
        :param chargeMode: (Optional) 计费模式
        :param chargeType: (Optional) 计费类型：0代表按增强95，1代表按95消峰，2代表主流量计费
        :param minBandwidth: (Optional) 允许的最小带宽，小于0表示不限制
        :param maxBandwidth: (Optional) 允许的最大带宽，小于0表示不限制
        """

        self.productCode = productCode
        self.chargeMode = chargeMode
        self.chargeType = chargeType
        self.minBandwidth = minBandwidth
        self.maxBandwidth = maxBandwidth
