# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class Ipv6Spec(object):

    def __init__(self, ipv6Id=None, ipv6Address=None):
        """
        :param ipv6Id: (Optional) ipv6公网ID，ipv6公网ID和公网IP二选一，不允许同时传入
        :param ipv6Address: (Optional) ipv6公网IP，ipv6公网IP和公网ID二选一，不允许同时传入
        """

        self.ipv6Id = ipv6Id
        self.ipv6Address = ipv6Address
