# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class NatGateway(object):

    def __init__(self, natGatewayId=None, natGatewayName=None, natGatewaySpec=None, state=None, description=None, natGatewayCharge=None, azs=None, vpcId=None, subnetId=None, azIp=None, createdTime=None):
        """
        :param natGatewayId: (Optional) NAT网关ID
        :param natGatewayName: (Optional) NAT网关名称
        :param natGatewaySpec: (Optional) NAT网关规格，取值small（100万并发连接数），medium（300万并发连接数），large（1000万并发连接数）
        :param state: (Optional) NAT网关的状态
        :param description: (Optional) NAT网关的描述信息
        :param natGatewayCharge: (Optional) NAT网关计费配置
        :param azs: (Optional) NAT网关可用区属性
        :param vpcId: (Optional) 私有网络ID
        :param subnetId: (Optional) 子网ID
        :param azIp: (Optional) NAT网关的IP可用区属性
        :param createdTime: (Optional) NAT网关创建时间
        """

        self.natGatewayId = natGatewayId
        self.natGatewayName = natGatewayName
        self.natGatewaySpec = natGatewaySpec
        self.state = state
        self.description = description
        self.natGatewayCharge = natGatewayCharge
        self.azs = azs
        self.vpcId = vpcId
        self.subnetId = subnetId
        self.azIp = azIp
        self.createdTime = createdTime
