# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class OpenIpv6AddressSpec(object):

    def __init__(self, bandwidthMbps, ipv6Id, chargeSpec=None):
        """
        :param bandwidthMbps:  ipv6带宽值，单位MB；取值范围：[1,200]
        :param ipv6Id:  ipv6的资源ID
        :param chargeSpec: (Optional) 计费配置。标准IPv6公网IP支持按配置、按流量
        """

        self.bandwidthMbps = bandwidthMbps
        self.ipv6Id = ipv6Id
        self.chargeSpec = chargeSpec
