# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class Provider(object):

    def __init__(self, provider=None, providerType=None, providerNameCN=None, productCodes=None, bandwidthLimits=None):
        """
        :param provider: (Optional) provider编码
        :param providerType: (Optional) provider类型，standard（中心）、edge（边缘）
        :param providerNameCN: (Optional) provider中文名称
        :param productCodes: (Optional) 产品编码。 支持:IP(弹性公网IP), BWP(共享带宽包), IPAP(公网IP地址池)
        :param bandwidthLimits: (Optional) 带宽限制
        """

        self.provider = provider
        self.providerType = providerType
        self.providerNameCN = providerNameCN
        self.productCodes = productCodes
        self.bandwidthLimits = bandwidthLimits
