# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class SnatRule(object):

    def __init__(self, sourceCidr, snatRuleId=None, description=None, snatElasticIpAddresses=None, subnetId=None, snatRuleStatus=None, snatRuleType=None, createdTime=None, updatedTime=None):
        """
        :param snatRuleId: (Optional) SNAT 规则ID
        :param description: (Optional) SNAT 规则描述
        :param snatElasticIpAddresses: (Optional) SNAT规则的公网IP地址
        :param sourceCidr:  SNAT 规则的源网段，如子网或云主机实例的网段
        :param subnetId: (Optional) 如果匹配上子网，输出该sourceCidr对应的子网
        :param snatRuleStatus: (Optional) SNAT 规则状态（ ENALBE - 启用； DISABLE - 禁用）
        :param snatRuleType: (Optional) SNAT 规则类型（ SYSTEM - 系统创建的； USER - 用户自定义的）
        :param createdTime: (Optional) 创建时间，时间格式为UTC
        :param updatedTime: (Optional) 修改时间，时间格式为UTC
        """

        self.snatRuleId = snatRuleId
        self.description = description
        self.snatElasticIpAddresses = snatElasticIpAddresses
        self.sourceCidr = sourceCidr
        self.subnetId = subnetId
        self.snatRuleStatus = snatRuleStatus
        self.snatRuleType = snatRuleType
        self.createdTime = createdTime
        self.updatedTime = updatedTime
