# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DeleteInstanceTemplateRequest(JDCloudRequest):
    """
    
删除单个实例模板。

详细操作说明请参考帮助文档：[删除实例模板](https://docs.jdcloud.com/cn/virtual-machines/delete-instance-template)

## 接口说明
- 关联了高可用组的实例模板不可以删除。

    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DeleteInstanceTemplateRequest, self).__init__(
            '/regions/{regionId}/instanceTemplates/{instanceTemplateId}', 'DELETE', header, version)
        self.parameters = parameters


class DeleteInstanceTemplateParameters(object):

    def __init__(self, regionId,instanceTemplateId,):
        """
        :param regionId: 地域ID。
        :param instanceTemplateId: 实例模板ID。
        """

        self.regionId = regionId
        self.instanceTemplateId = instanceTemplateId

