# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class PodStatus(object):

    def __init__(self, phase=None, reason=None, message=None, podIP=None, conditions=None, startTime=None):
        """
        :param phase: (Optional) pod当前状态
        :param reason: (Optional) （简要）pod处于当前状态的原因
        :param message: (Optional) pod处于当前状态原因的详细信息
        :param podIP: (Optional) 分配给pod的IP地址。至少在集群内是可路由的。未分配则为空。
        :param conditions: (Optional) 目前pod的状态。
        :param startTime: (Optional) Pod生命周期开始的时间。
        """

        self.phase = phase
        self.reason = reason
        self.message = message
        self.podIP = podIP
        self.conditions = conditions
        self.startTime = startTime
