# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ContractInfo(object):

    def __init__(self, contractId=None, contractTitle=None, stampNames=None, contractContent=None, contractDigest=None, createTime=None):
        """
        :param contractId: (Optional) 合同ID
        :param contractTitle: (Optional) 合同标题
        :param stampNames: (Optional) 印章名称(可能有多个印章)
        :param contractContent: (Optional) 合同文件（base64）
        :param contractDigest: (Optional) 合同文件摘要
        :param createTime: (Optional) 合同签章时间
        """

        self.contractId = contractId
        self.contractTitle = contractTitle
        self.stampNames = stampNames
        self.contractContent = contractContent
        self.contractDigest = contractDigest
        self.createTime = createTime
