# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class PackInfo(object):

    def __init__(self, packageType=None, from_=None, totalAmount=None, balanceAmount=None, startTime=None, endTime=None, packId=None):
        """
        :param packageType: (Optional) 资源包类型
        :param from_: (Optional) 来源，1-免费，2-付费
        :param totalAmount: (Optional) 总用量
        :param balanceAmount: (Optional) 剩余用量
        :param startTime: (Optional) 生效时间
        :param endTime: (Optional) 失效时间
        :param packId: (Optional) 资源包id
        """

        self.packageType = packageType
        self.from_ = from_
        self.totalAmount = totalAmount
        self.balanceAmount = balanceAmount
        self.startTime = startTime
        self.endTime = endTime
        self.packId = packId
