# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class AddCustomStarRocksUserRequest(JDCloudRequest):
    """
    创建实例的自定义用户，独立于IAM同名用户之外，这个用户和实例操作无关，只是一个starRocks数据库的用户
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(AddCustomStarRocksUserRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/addCustomStarRocksUser', 'POST', header, version)
        self.parameters = parameters


class AddCustomStarRocksUserParameters(object):

    def __init__(self,regionId, appName, projectCode, userName, passWord):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        :param projectCode: 实例code
        :param userName: 用户名
        :param passWord: 密码
        """

        self.regionId = regionId
        self.appName = appName
        self.projectCode = projectCode
        self.userName = userName
        self.passWord = passWord

