# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DevelopMenuDeleteRequest(JDCloudRequest):
    """
    节点删除，必须的参数：projectCode、code
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DevelopMenuDeleteRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/developMenuDelete', 'POST', header, version)
        self.parameters = parameters


class DevelopMenuDeleteParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.projectCode = None
        self.code = None
        self.name = None
        self.parentMenuCode = None
        self.targetMenuCode = None
        self.isDir = None
        self.developTaskType = None

    def setProjectCode(self, projectCode):
        """
        :param projectCode: (Optional) 项目实例Code
        """
        self.projectCode = projectCode

    def setCode(self, code):
        """
        :param code: (Optional) 目录id，修改、移动、删除时必传
        """
        self.code = code

    def setName(self, name):
        """
        :param name: (Optional) 目录名称、创建、修改时必须传
        """
        self.name = name

    def setParentMenuCode(self, parentMenuCode):
        """
        :param parentMenuCode: (Optional) 父目录id，创建、移动时必须传
        """
        self.parentMenuCode = parentMenuCode

    def setTargetMenuCode(self, targetMenuCode):
        """
        :param targetMenuCode: (Optional) 目标目录id，移动时必须传
        """
        self.targetMenuCode = targetMenuCode

    def setIsDir(self, isDir):
        """
        :param isDir: (Optional) 是否是目录，true是目录，false是task
        """
        self.isDir = isDir

    def setDevelopTaskType(self, developTaskType):
        """
        :param developTaskType: (Optional) 排序方向
        """
        self.developTaskType = developTaskType

