# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class RoleAddTablePrivilegeRequest(JDCloudRequest):
    """
    添加表、视图、物化视图权限
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(RoleAddTablePrivilegeRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/roleAddTablePrivilege', 'POST', header, version)
        self.parameters = parameters


class RoleAddTablePrivilegeParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.projectCode = None
        self.role = None
        self.tableModel = None
        self.roleTablePrivilegeList = None

    def setProjectCode(self, projectCode):
        """
        :param projectCode: (Optional) 项目ID
        """
        self.projectCode = projectCode

    def setRole(self, role):
        """
        :param role: (Optional) 角色名称
        """
        self.role = role

    def setTableModel(self, tableModel):
        """
        :param tableModel: (Optional) 表类型
        """
        self.tableModel = tableModel

    def setRoleTablePrivilegeList(self, roleTablePrivilegeList):
        """
        :param roleTablePrivilegeList: (Optional) 权限明细
        """
        self.roleTablePrivilegeList = roleTablePrivilegeList

