# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class WarehouseGetListRequest(JDCloudRequest):
    """
    分页查询资源分组列表
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(WarehouseGetListRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/warehouseGetList', 'POST', header, version)
        self.parameters = parameters


class WarehouseGetListParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.currentPage = None
        self.pageSize = None
        self.sort = None
        self.order = None
        self.data = None

    def setCurrentPage(self, currentPage):
        """
        :param currentPage: (Optional) 分页页码
        """
        self.currentPage = currentPage

    def setPageSize(self, pageSize):
        """
        :param pageSize: (Optional) 分页大小
        """
        self.pageSize = pageSize

    def setSort(self, sort):
        """
        :param sort: (Optional) 排序字段
        """
        self.sort = sort

    def setOrder(self, order):
        """
        :param order: (Optional) 排序方向
        """
        self.order = order

    def setData(self, data):
        """
        :param data: (Optional) 
        """
        self.data = data

