# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DescribeLiveRecordFileUrlRequest(JDCloudRequest):
    """
    获取录制文件地址

    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DescribeLiveRecordFileUrlRequest, self).__init__(
            '/recordFiles/{fileId}:url', 'GET', header, version)
        self.parameters = parameters


class DescribeLiveRecordFileUrlParameters(object):

    def __init__(self, fileId, ):
        """
        :param fileId: 录制文件ID

        """

        self.fileId = fileId
        self.authExpire = None

    def setAuthExpire(self, authExpire):
        """
        :param authExpire: (Optional) 地址有效期，单位：秒，默认：3600，最大支持7天

        """
        self.authExpire = authExpire

