# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class HpcNetDiagnose(object):

    def __init__(self, id=None, az=None, region=None, vpcId=None, hpcClusterName=None, type=None, traffic=None, port=None, createTime=None, endTime=None, status=None, duration=None, qp=None, gdr=None, results=None):
        """
        :param id: (Optional) 诊断报告ID
        :param az: (Optional) 可用区
        :param region: (Optional) 地域
        :param vpcId: (Optional) vpc id
        :param hpcClusterName: (Optional) 集群名字
        :param type: (Optional) LATENCY:时延测试；BANDWIDTH:带宽测试；
        :param traffic: (Optional) MTON,FULLMESH (带宽测试独有)
        :param port: (Optional) 端口 5000-65535
        :param createTime: (Optional) 创建时间
        :param endTime: (Optional) 结束时间
        :param status: (Optional) 诊断报告完成状态(取值：INIT：初始化；FINISH：已完成；PROCESS：处理中；ERROR:错误)
        :param duration: (Optional) 测试时长 （带宽测试独有）
        :param qp: (Optional) qp [1-16384]（带宽测试独有）
        :param gdr: (Optional) 是否启用 GDR（带宽测试独有）
        :param results: (Optional) 测试结果
        """

        self.id = id
        self.az = az
        self.region = region
        self.vpcId = vpcId
        self.hpcClusterName = hpcClusterName
        self.type = type
        self.traffic = traffic
        self.port = port
        self.createTime = createTime
        self.endTime = endTime
        self.status = status
        self.duration = duration
        self.qp = qp
        self.gdr = gdr
        self.results = results
