# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class AiOpsListRayTaskInstancesRequest(JDCloudRequest):
    """
    Ray 任务运行记录查询
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(AiOpsListRayTaskInstancesRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/aiOpsListRayTaskInstances', 'POST', header, version)
        self.parameters = parameters


class AiOpsListRayTaskInstancesParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.pageNo = None
        self.pageSize = None
        self.taskId = None
        self.stateList = None
        self.startTimeStart = None
        self.startTimeEnd = None
        self.workspaceCode = None
        self.companyCode = None

    def setPageNo(self, pageNo):
        """
        :param pageNo: (Optional) 页码
        """
        self.pageNo = pageNo

    def setPageSize(self, pageSize):
        """
        :param pageSize: (Optional) 每页条数
        """
        self.pageSize = pageSize

    def setTaskId(self, taskId):
        """
        :param taskId: (Optional) 任务ID
        """
        self.taskId = taskId

    def setStateList(self, stateList):
        """
        :param stateList: (Optional) 实例状态
        """
        self.stateList = stateList

    def setStartTimeStart(self, startTimeStart):
        """
        :param startTimeStart: (Optional) 开始时间起（时间戳，毫秒）
        """
        self.startTimeStart = startTimeStart

    def setStartTimeEnd(self, startTimeEnd):
        """
        :param startTimeEnd: (Optional) 开始时间止（时间戳，毫秒）
        """
        self.startTimeEnd = startTimeEnd

    def setWorkspaceCode(self, workspaceCode):
        """
        :param workspaceCode: (Optional) 工作空间编码
        """
        self.workspaceCode = workspaceCode

    def setCompanyCode(self, companyCode):
        """
        :param companyCode: (Optional) 租户编码
        """
        self.companyCode = companyCode

