# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DataWorkshopSwitchClusterRequest(JDCloudRequest):
    """
    切换集群状态
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DataWorkshopSwitchClusterRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/dataWorkshopSwitchCluster', 'POST', header, version)
        self.parameters = parameters


class DataWorkshopSwitchClusterParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.clusterId = None
        self.enable = None

    def setClusterId(self, clusterId):
        """
        :param clusterId: (Optional) 集群ID
        """
        self.clusterId = clusterId

    def setEnable(self, enable):
        """
        :param enable: (Optional) 集群是否启动：true-启动集群，false-停止集群
        """
        self.enable = enable

