# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DataWorkShopExpandOrShrinkRequest(JDCloudRequest):
    """
    资源组扩缩容
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DataWorkShopExpandOrShrinkRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/dataWorkShopExpandOrShrink', 'POST', header, version)
        self.parameters = parameters


class DataWorkShopExpandOrShrinkParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.resourceCode = None
        self.resourceChangeType = None
        self.targetCus = None
        self.targetGpus = None
        self.deadtime = None
        self.returnUrl = None

    def setResourceCode(self, resourceCode):
        """
        :param resourceCode: (Optional) 资源code
        """
        self.resourceCode = resourceCode

    def setResourceChangeType(self, resourceChangeType):
        """
        :param resourceChangeType: (Optional) 资源变更类型 扩容：expanding，缩容：shrinking，临时升配：expansion_temporary
        """
        self.resourceChangeType = resourceChangeType

    def setTargetCus(self, targetCus):
        """
        :param targetCus: (Optional) 目标cu数
        """
        self.targetCus = targetCus

    def setTargetGpus(self, targetGpus):
        """
        :param targetGpus: (Optional) 目标gpu数
        """
        self.targetGpus = targetGpus

    def setDeadtime(self, deadtime):
        """
        :param deadtime: (Optional) 变更后需要恢复变更前cu数的时间点
        """
        self.deadtime = deadtime

    def setReturnUrl(self, returnUrl):
        """
        :param returnUrl: (Optional) 购买时跳转url
        """
        self.returnUrl = returnUrl

