# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class MetaUnifierListModelRequest(JDCloudRequest):
    """
    列出模型
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(MetaUnifierListModelRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/metaUnifierListModel', 'POST', header, version)
        self.parameters = parameters


class MetaUnifierListModelParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.pageNum = None
        self.pageSize = None
        self.companyCode = None
        self.catalogName = None
        self.schemaName = None
        self.modelName = None

    def setPageNum(self, pageNum):
        """
        :param pageNum: (Optional) 
        """
        self.pageNum = pageNum

    def setPageSize(self, pageSize):
        """
        :param pageSize: (Optional) 
        """
        self.pageSize = pageSize

    def setCompanyCode(self, companyCode):
        """
        :param companyCode: (Optional) 租户code
        """
        self.companyCode = companyCode

    def setCatalogName(self, catalogName):
        """
        :param catalogName: (Optional) catalog名称
        """
        self.catalogName = catalogName

    def setSchemaName(self, schemaName):
        """
        :param schemaName: (Optional) schema名称
        """
        self.schemaName = schemaName

    def setModelName(self, modelName):
        """
        :param modelName: (Optional) 模型名称
        """
        self.modelName = modelName

