# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class MetaUnifierDeleteFileSetRequest(JDCloudRequest):
    """
    根据catalogName、schemaName、filesetName删除文件集 rest接口
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(MetaUnifierDeleteFileSetRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/metaUnifierDeleteFileSet', 'POST', header, version)
        self.parameters = parameters


class MetaUnifierDeleteFileSetParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.companyCode = None
        self.catalogName = None
        self.schemaName = None
        self.filesetName = None

    def setCompanyCode(self, companyCode):
        """
        :param companyCode: (Optional) 租户code
        """
        self.companyCode = companyCode

    def setCatalogName(self, catalogName):
        """
        :param catalogName: (Optional) catalog名称，必传
        """
        self.catalogName = catalogName

    def setSchemaName(self, schemaName):
        """
        :param schemaName: (Optional) schema名称，必传
        """
        self.schemaName = schemaName

    def setFilesetName(self, filesetName):
        """
        :param filesetName: (Optional) fileset名称，必传
        """
        self.filesetName = filesetName

