# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class MetaUnifierGetTableRequest(JDCloudRequest):
    """
    获取表 rest接口
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(MetaUnifierGetTableRequest, self).__init__(
            '/regions/{regionId}/apps/{appName}/metaUnifierGetTable', 'POST', header, version)
        self.parameters = parameters


class MetaUnifierGetTableParameters(object):

    def __init__(self,regionId, appName, ):
        """
        :param regionId: 地域ID
        :param appName: 应用名称
        """

        self.regionId = regionId
        self.appName = appName
        self.companyCode = None
        self.catalogName = None
        self.schemaName = None
        self.tableName = None
        self.comment = None
        self.metaType = None
        self.partition = None
        self.owner = None
        self.distributionStrategy = None
        self.bucketCount = None
        self.fieldInfos = None
        self.properties = None

    def setCompanyCode(self, companyCode):
        """
        :param companyCode: (Optional) 租户code
        """
        self.companyCode = companyCode

    def setCatalogName(self, catalogName):
        """
        :param catalogName: (Optional) catalog名称
        """
        self.catalogName = catalogName

    def setSchemaName(self, schemaName):
        """
        :param schemaName: (Optional) schema名称
        """
        self.schemaName = schemaName

    def setTableName(self, tableName):
        """
        :param tableName: (Optional) 表名称
        """
        self.tableName = tableName

    def setComment(self, comment):
        """
        :param comment: (Optional) 描述
        """
        self.comment = comment

    def setMetaType(self, metaType):
        """
        :param metaType: (Optional) 元数据类型(iceberg/lance/fileset/paimon)
        """
        self.metaType = metaType

    def setPartition(self, partition):
        """
        :param partition: (Optional) 是否分区
        """
        self.partition = partition

    def setOwner(self, owner):
        """
        :param owner: (Optional) owner
        """
        self.owner = owner

    def setDistributionStrategy(self, distributionStrategy):
        """
        :param distributionStrategy: (Optional) 数据分布策略， NONE：无策略；HASH：基于hash分区分布；RANGE：范围分布，自动基于排序列/分区列
        """
        self.distributionStrategy = distributionStrategy

    def setBucketCount(self, bucketCount):
        """
        :param bucketCount: (Optional) 桶数量（Paimon distribution 使用）。为空表示 AUTO，由引擎自动决定桶数；仅 distributionStrategy=HASH 时生效
        """
        self.bucketCount = bucketCount

    def setFieldInfos(self, fieldInfos):
        """
        :param fieldInfos: (Optional) 
        """
        self.fieldInfos = fieldInfos

    def setProperties(self, properties):
        """
        :param properties: (Optional) properties
        """
        self.properties = properties

