# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AggregatedTaskItem(object):

    def __init__(self, taskId=None, taskName=None, taskType=None, workspaceId=None, workspaceName=None, creator=None, priority=None, taskStatus=None, creationTime=None, deletionTime=None, queueDurationSeconds=None, runningDurationSeconds=None):
        """
        :param taskId: (Optional) 任务ID
        :param taskName: (Optional) 任务名称
        :param taskType: (Optional) 任务类型
        :param workspaceId: (Optional) 工作空间ID
        :param workspaceName: (Optional) 工作空间名称
        :param creator: (Optional) 创建人
        :param priority: (Optional) 任务优先级，从 DescribeResources 取，取不到默认 5
        :param taskStatus: (Optional) 任务状态
        :param creationTime: (Optional) 创建时间
        :param deletionTime: (Optional) 删除时间
        :param queueDurationSeconds: (Optional) 排队时长(秒)
        :param runningDurationSeconds: (Optional) 运行时长(秒)
        """

        self.taskId = taskId
        self.taskName = taskName
        self.taskType = taskType
        self.workspaceId = workspaceId
        self.workspaceName = workspaceName
        self.creator = creator
        self.priority = priority
        self.taskStatus = taskStatus
        self.creationTime = creationTime
        self.deletionTime = deletionTime
        self.queueDurationSeconds = queueDurationSeconds
        self.runningDurationSeconds = runningDurationSeconds
