# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class AutoScale(object):

    def __init__(self, minReplicaCount, maxReplicaCount, scaleUpDelay=None, scaleDownDelay=None, cpuThreshold=None, gpuThreshold=None, memoryThreshold=None):
        """
        :param minReplicaCount:  最小副本数
        :param maxReplicaCount:  最大副本数
        :param scaleUpDelay: (Optional) 扩容延迟时间（秒）
        :param scaleDownDelay: (Optional) 缩容延迟时间（秒）
        :param cpuThreshold: (Optional) CPU使用率阈值（%，基于Limits）
        :param gpuThreshold: (Optional) GPU利用率阈值（%）
        :param memoryThreshold: (Optional) 内存使用率阈值（%，基于Limits）
        """

        self.minReplicaCount = minReplicaCount
        self.maxReplicaCount = maxReplicaCount
        self.scaleUpDelay = scaleUpDelay
        self.scaleDownDelay = scaleDownDelay
        self.cpuThreshold = cpuThreshold
        self.gpuThreshold = gpuThreshold
        self.memoryThreshold = memoryThreshold
