# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ClusterSimple(object):

    def __init__(self, id=None, name=None, status=None, msg=None, region=None):
        """
        :param id: (Optional) 集群ID
        :param name: (Optional) 集群名称
        :param status: (Optional) 状态，creating:创建中；init:初始化；ready:成功；fail:错误
        :param msg: (Optional) 错误信息
        :param region: (Optional) 地域
        """

        self.id = id
        self.name = name
        self.status = status
        self.msg = msg
        self.region = region
