# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class FaultGPUStatistics(object):

    def __init__(self, nodeName=None, cluster=None, nodeGroup=None, nodeIp=None, model=None, brand=None, uuid=None, errorMessage=None):
        """
        :param nodeName: (Optional) 节点名称
        :param cluster: (Optional) 集群ID
        :param nodeGroup: (Optional) 节点组信息
        :param nodeIp: (Optional) 节点IP地址
        :param model: (Optional) 显卡型号
        :param brand: (Optional) 显卡品牌
        :param uuid: (Optional) 显卡UUID
        :param errorMessage: (Optional) 错误信息
        """

        self.nodeName = nodeName
        self.cluster = cluster
        self.nodeGroup = nodeGroup
        self.nodeIp = nodeIp
        self.model = model
        self.brand = brand
        self.uuid = uuid
        self.errorMessage = errorMessage
