# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ModelBillingConfig(object):

    def __init__(self, usage, modelName, stream, dataType, maxTokens, billingCode, price, chargeDivisor, chargeUnit, label, description=None):
        """
        :param usage:  用途(distill,train)
        :param modelName:  模型名称
        :param stream:  输入输出(input,output)
        :param dataType:  数据类型(text,image,audio,video)
        :param maxTokens:  Tokens上限
        :param billingCode:  计费项
        :param price:  单价
        :param chargeDivisor:  上报除数(比如计价规格为千Tokens，上报时就要除1000)
        :param chargeUnit:  上报单位
        :param label:  展示信息
        :param description: (Optional) 说明
        """

        self.usage = usage
        self.modelName = modelName
        self.stream = stream
        self.dataType = dataType
        self.maxTokens = maxTokens
        self.billingCode = billingCode
        self.price = price
        self.chargeDivisor = chargeDivisor
        self.chargeUnit = chargeUnit
        self.label = label
        self.description = description
