# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ModelSpecPrivate(object):

    def __init__(self, modelName=None, modelId=None, description=None, storageType=None, storageDomain=None, storageBucket=None, storagePath=None, storageId=None, labels=None, basicModelId=None, experimentId=None, experimentRunId=None, sourceType=None, permission=None):
        """
        :param modelName: (Optional) 模型名称（创建【新模型】生效且必填）。
命名规则：1~128字符，仅支持中文、大小写字母、数字、英文中划线“-”、英文下划线“_”和点 “.”。

        :param modelId: (Optional) 模型ID（创建【新版本】生效且必填）。示例：model-yp****qu
        :param description: (Optional) 模型描述/版本描述。若创建新模型，为模型描述与版本V1的描述；若创建新版本，为新版本描述。
        :param storageType: (Optional) 存储类型（数据集来源），可选值：
- oss
- cfs
- jpfs

        :param storageDomain: (Optional) storageType=oss时必传，对象存储（OSS）域名
        :param storageBucket: (Optional) storageType=oss时必传，对象存储（OSS）bucket
        :param storagePath: (Optional) 存储path（数据来源path）
例如：
- 对象存储（OSS）时，传bucket后面部分的路径；
- cfs时，虚根pseudo后面部分的路径

        :param storageId: (Optional) 存储ID，storageType=cfs或jpfs时必传，例如：fs-60****ui
        :param labels: (Optional) 标签，多个标签使用英文逗号拼接。例如：label1,label2,label3
        :param basicModelId: (Optional) 基础模型ID(下游任务模块[训练任务/精调实验等]创建模型使用)。
        :param experimentId: (Optional) 注册来源对应的ID：训练任务ID/精调实验ID等
        :param experimentRunId: (Optional) 训练任务/精调实验等的运行记录id
        :param sourceType: (Optional) 注册来源：finetune精调实验。 默认值user为用户上传。
        :param permission: (Optional) 模型资源归属权限（创建【新模型】生效），支持(public,private)，默认为public。
        """

        self.modelName = modelName
        self.modelId = modelId
        self.description = description
        self.storageType = storageType
        self.storageDomain = storageDomain
        self.storageBucket = storageBucket
        self.storagePath = storagePath
        self.storageId = storageId
        self.labels = labels
        self.basicModelId = basicModelId
        self.experimentId = experimentId
        self.experimentRunId = experimentRunId
        self.sourceType = sourceType
        self.permission = permission
