# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class NodePool(object):

    def __init__(self, id=None, name=None, bizType=None, poolType=None, chargeType=None, nodeCount=None, topology=None, status=None, rdma=None, msg=None, enable=None, createTime=None, hpcCluster=None, hpcClusterName=None, hpcZone=None, desc=None, gpuQuotas=None, cpuQuota=None, cluster=None, userTags=None, resourceGroupId=None, resourceGroupName=None, overview=None):
        """
        :param id: (Optional) 节点池ID
        :param name: (Optional) 节点池名称
        :param bizType: (Optional) 业务类型-离线/在线/混部
        :param poolType: (Optional) 节点池类型，combined：异构节点池；general：云主机节点池；mixture：混合节点池
        :param chargeType: (Optional) 计费方式，pack：包年包月；advance：预付费
        :param nodeCount: (Optional) 节点数量
        :param topology: (Optional) 是否支持网络拓扑；0：不支持，1：支持
        :param status: (Optional) 状态，creating:创建中；ready:运行中；fail:创建失败
        :param rdma: (Optional) 是否支持rdma网络
        :param msg: (Optional) 错误信息
        :param enable: (Optional) 是否启用
        :param createTime: (Optional) 创建时间，秒
        :param hpcCluster: (Optional) hpc节点所属物理集群
        :param hpcClusterName: (Optional) hpc节点所在物理集群名称
        :param hpcZone: (Optional) hpc节点所属可用区
        :param desc: (Optional) 节点池名称
        :param gpuQuotas: (Optional) GPU资源配额信息
        :param cpuQuota: (Optional) 资源配额信息
        :param cluster: (Optional) 
        :param userTags: (Optional) Tag信息
        :param resourceGroupId: (Optional) 资源组Id
        :param resourceGroupName: (Optional) 资源组名称
        :param overview: (Optional) 节点池概览信息
        """

        self.id = id
        self.name = name
        self.bizType = bizType
        self.poolType = poolType
        self.chargeType = chargeType
        self.nodeCount = nodeCount
        self.topology = topology
        self.status = status
        self.rdma = rdma
        self.msg = msg
        self.enable = enable
        self.createTime = createTime
        self.hpcCluster = hpcCluster
        self.hpcClusterName = hpcClusterName
        self.hpcZone = hpcZone
        self.desc = desc
        self.gpuQuotas = gpuQuotas
        self.cpuQuota = cpuQuota
        self.cluster = cluster
        self.userTags = userTags
        self.resourceGroupId = resourceGroupId
        self.resourceGroupName = resourceGroupName
        self.overview = overview
