# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class PublicImageInfo(object):

    def __init__(self, imageId=None, imageName=None, imageUsage=None, imageType=None, imageUrl=None, sourceType=None, labels=None, labelList=None, command=None, pin=None, createUser=None, createTime=None, updateTime=None, updateUser=None, online=None):
        """
        :param imageId: (Optional) 镜像ID。 示例：img-lh****3p
        :param imageName: (Optional) 镜像名称
        :param imageUsage: (Optional) 镜像用途，可选值：
- notebook:Notebook
- training:训练任务
- inference:在线服务，
- finetune:精调实验
- simulation:仿真任务
- offlineTask:离线任务

示例：notebook,training,inference

        :param imageType: (Optional) 镜像类型：cpu,gpu
        :param imageUrl: (Optional) 镜像地址。
示例：aip-public-sq-cn-east-1.jcr.service.jdcloud.com/serving/vllm:minimaxm3-vllm0.1.dev17492-pytorch2.11.0-transformers5.11.0-cu13.0-gpu-py3.12.13-ubuntu22.04

        :param sourceType: (Optional) 注册方式，可选值：
- jcr 容器镜像仓库注册，公共镜像仅支持已有镜像注册

        :param labels: (Optional) 标签，使用英文逗号拼接。
示例：baseinfo:vllm0.25.0,baseinfo:pytorch2.11.0,baseinfo:transformers5.13.0,baseinfo:cuda13.0,baseinfo:gpu,baseinfo:python3.12.3,baseinfo:ubuntu24.04,baseinfo:jupyterlab,baseinfo:vscode,protocol:http,protocol:grpc

        :param labelList: (Optional) 标签，labels转换的数组格式, 仅包含baseinfo对应的标签。
        :param command: (Optional) 镜像启动命令。
        :param pin: (Optional) 主账号pin
        :param createUser: (Optional) 创建人
        :param createTime: (Optional) 创建时间
        :param updateTime: (Optional) 更新时间
        :param updateUser: (Optional) 更新用户
        :param online: (Optional) true上线，false下线。
        """

        self.imageId = imageId
        self.imageName = imageName
        self.imageUsage = imageUsage
        self.imageType = imageType
        self.imageUrl = imageUrl
        self.sourceType = sourceType
        self.labels = labels
        self.labelList = labelList
        self.command = command
        self.pin = pin
        self.createUser = createUser
        self.createTime = createTime
        self.updateTime = updateTime
        self.updateUser = updateUser
        self.online = online
