# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class SchedulePolicy(object):

    def __init__(self, schedulePolicy=None, preemptionPolicy=None, borrowPolicy=None, reclaimPolicy=None):
        """
        :param schedulePolicy: (Optional) **调度策略**，可选：StrictFIFO，BestEffortFIFO，默认值为：BestEffortFIFO
- **StrictFIFO**：严格先入先出，
- **BestEffortFIFO**：优先调度

        :param preemptionPolicy: (Optional) **抢占策略**，可选：Never、LowPriority、LowOrNewerEqualPriority，默认值为：LowPriority
**抢占范围**：当前同资源队列
- **Never**： 不抢占
- **LowPriority**：抢占优先级低的任务
- **LowOrNewerEqualPriority**：抢占优先级低或者比自己晚创建的任务资源

        :param borrowPolicy: (Optional) **借用抢占策略**，可选：Never、LowPriority，默认值为：Never
借用抢占范围：同一个资源组下的资源队列
- **Never**: 借用资源时不发生抢占
- **LowPriority**: 借用资源时抢占优先级低的任务资源

        :param reclaimPolicy: (Optional) **归还抢占策略**，可选：Never、LowPriority、Any，默认值为：Any
- **Never**: 归还资源时不发生抢占
- **LowPriority**: 归还资源时抢占优先级低的任务资源
- **Any**: 强制归还被借用资源

        """

        self.schedulePolicy = schedulePolicy
        self.preemptionPolicy = preemptionPolicy
        self.borrowPolicy = borrowPolicy
        self.reclaimPolicy = reclaimPolicy
