# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class SimulationDetail(object):

    def __init__(self, pin=None, createUser=None, createUserPin=None, ownerUser=None, ownerUserPin=None, updateUser=None, updateUserPin=None, createTime=None, updateTime=None, simulationId=None, name=None, description=None, permission=None, taskId=None, state=None, resourceState=None, workspaceId=None, workspaceName=None, reason=None, runningTime=None, terminalUrl=None, imageInfo=None, workloadInfo=None, logCollect=None, nodeAffinities=None, lb=None, storages=None, datasets=None):
        """
        :param pin: (Optional) 主帐号。
        :param createUser: (Optional) 创建人用户名。
        :param createUserPin: (Optional) 创建人pin。
        :param ownerUser: (Optional) 归属用户名称。
        :param ownerUserPin: (Optional) 归属用户pin。
        :param updateUser: (Optional) 最后更新的用户名。
        :param updateUserPin: (Optional) 最后更新的用户pin。
        :param createTime: (Optional) 创建时间。
        :param updateTime: (Optional) 更新时间。
        :param simulationId: (Optional) 仿真资源ID。
        :param name: (Optional) 名称。
        :param description: (Optional) 描述。
        :param permission: (Optional) 工作空间中的资源归属权限。
        :param taskId: (Optional) 任务ID，不为空表示正在执行任务。
        :param state: (Optional) 状态：
- queuing: 队排中。
- pending: 启动中。
- failed: 失败。
- running: 运行中。
- stopping: 停止中。
- stopped: 已停止。
- deleting: 删除中。

        :param resourceState: (Optional) 资源在集群中的空闲状态，值为空表示是空闲的，in-use表示资源已被占用。

        :param workspaceId: (Optional) 工作空间ID。
        :param workspaceName: (Optional) 工作空间名称。
        :param reason: (Optional) 异常原因。
        :param runningTime: (Optional) 开始运行时间，如(2023-06-01 12:22:56)。
        :param terminalUrl: (Optional) 仿真容器终端地址。
        :param imageInfo: (Optional) 镜像信息。
        :param workloadInfo: (Optional) 工作负载资源配置。
        :param logCollect: (Optional) 日志采集配置。
        :param nodeAffinities: (Optional) 节点亲和性配置。
        :param lb: (Optional) 公网访问配置。
        :param storages: (Optional) 存储配置。
        :param datasets: (Optional) 数据集配置。
        """

        self.pin = pin
        self.createUser = createUser
        self.createUserPin = createUserPin
        self.ownerUser = ownerUser
        self.ownerUserPin = ownerUserPin
        self.updateUser = updateUser
        self.updateUserPin = updateUserPin
        self.createTime = createTime
        self.updateTime = updateTime
        self.simulationId = simulationId
        self.name = name
        self.description = description
        self.permission = permission
        self.taskId = taskId
        self.state = state
        self.resourceState = resourceState
        self.workspaceId = workspaceId
        self.workspaceName = workspaceName
        self.reason = reason
        self.runningTime = runningTime
        self.terminalUrl = terminalUrl
        self.imageInfo = imageInfo
        self.workloadInfo = workloadInfo
        self.logCollect = logCollect
        self.nodeAffinities = nodeAffinities
        self.lb = lb
        self.storages = storages
        self.datasets = datasets
