# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class VisiblePool(object):

    def __init__(self, clusterId=None, poolId=None, poolName=None, description=None, poolType=None, category=None, hpcClusterName=None):
        """
        :param clusterId: (Optional) 所属集群ID。
        :param poolId: (Optional) 资源池ID。
        :param poolName: (Optional) 资源池名称。默认由 Scale GetNodePool 接口获取；force=true 且 Scale 不可用时可作为兜底值。
        :param description: (Optional) 资源池描述。
        :param poolType: (Optional) 资源池类型。`public` 为公共资源池，`exclusive` 为专享公共池。
        :param category: (Optional) 资源池规格类型。
        :param hpcClusterName: (Optional) HPC物理集群名称。
        """

        self.clusterId = clusterId
        self.poolId = poolId
        self.poolName = poolName
        self.description = description
        self.poolType = poolType
        self.category = category
        self.hpcClusterName = hpcClusterName
