# coding=utf8

# Copyright 2018-2025 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class DescribeMetricsRequest(JDCloudRequest):
    """
    根据产品线查询可用监控项列表
    """

    def __init__(self, parameters, header=None, version="v1"):
        super(DescribeMetricsRequest, self).__init__(
            '/metrics', 'GET', header, version)
        self.parameters = parameters


class DescribeMetricsParameters(object):

    def __init__(self, serviceCode):
        """
        :param serviceCode: 资源的类型 ： 
vm-->云主机
disk-->云硬盘
ip-->公网ip
balance-->负载均衡
database-->云数据库mysql版本
cdn-->京东CDN
redis-->redis云缓存
mongodb-->mongoDB云缓存
storage-->云存储
sqlserver-->云数据库sqlserver版 
nativecontainer-->容器

        """

        self.serviceCode = serviceCode

