# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.

from jdcloud_sdk.core.jdcloudrequest import JDCloudRequest


class ManualActionRequest(JDCloudRequest):
    """
    查询多个指定流水线执行及状态信息

    """

    def __init__(self, parameters, header=None, version="v1"):
        super(ManualActionRequest, self).__init__(
            '/regions/{regionId}/pipeline/{uuid}/instances/{instanceUuid}/actions/{actionUuid}:manual', 'POST', header, version)
        self.parameters = parameters


class ManualActionParameters(object):

    def __init__(self, regionId, uuid, instanceUuid, actionUuid, status):
        """
        :param regionId: Region ID
        :param uuid: 流水线uuid
        :param instanceUuid: 流水线实例uuid
        :param actionUuid: 动作UUID
        :param status: 手动设置的状态，如SUCCESS,FAILED
        """

        self.regionId = regionId
        self.uuid = uuid
        self.instanceUuid = instanceUuid
        self.actionUuid = actionUuid
        self.status = status

