# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class OCRInfo(object):

    def __init__(self, status=None, name=None, nation=None, address=None, idNumber=None, birthday=None, gender=None):
        """
        :param status: (Optional) normal-识别正常
reversed_side-身份证正反面颠倒
non_idcard-上传的图片中不包含身份证
blurred-身份证模糊
other_type_card-其他类型证照
over_exposure-身份证关键字段反光或过曝
over_dark-身份证欠曝（亮度过低）
unknown-未知状态

        :param name: (Optional) 姓名
        :param nation: (Optional) 民族
        :param address: (Optional) 住址
        :param idNumber: (Optional) 身份证号
        :param birthday: (Optional) 出生日期
        :param gender: (Optional) 性别
        """

        self.status = status
        self.name = name
        self.nation = nation
        self.address = address
        self.idNumber = idNumber
        self.birthday = birthday
        self.gender = gender
