# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class Bgp(object):

    def __init__(self, addressFamily=None, customerAsn=None, jdCloudAsn=None, authKey=None):
        """
        :param addressFamily: (Optional) BgpPeer的地址簇：目前仅支持ipv4
        :param customerAsn: (Optional) 用户侧AS
        :param jdCloudAsn: (Optional) 京东云侧AS
        :param authKey: (Optional) Bgp配置的认证key
        """

        self.addressFamily = addressFamily
        self.customerAsn = customerAsn
        self.jdCloudAsn = jdCloudAsn
        self.authKey = authKey
