# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class CustomerGateway(object):

    def __init__(self, customerGatewayId=None, customerGatewayName=None, customerIps=None, bgpAsn=None, description=None, createdTime=None, updatedTime=None):
        """
        :param customerGatewayId: (Optional) 客户网关的Id
        :param customerGatewayName: (Optional) 客户网关的名称
        :param customerIps: (Optional) 客户网关上的IP列表
        :param bgpAsn: (Optional) 客户自治系统的ASN号
        :param description: (Optional) 客户网关的描述
        :param createdTime: (Optional) 客户网关的创建时间
        :param updatedTime: (Optional) 客户网关的更新时间
        """

        self.customerGatewayId = customerGatewayId
        self.customerGatewayName = customerGatewayName
        self.customerIps = customerIps
        self.bgpAsn = bgpAsn
        self.description = description
        self.createdTime = createdTime
        self.updatedTime = updatedTime
