# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class Account(object):

    def __init__(self, id=None, userPin=None, accountId=None, serviceIp=None, key=None, keyStatus=None, createTime=None, updateTime=None, noauthAccess=None, domainLimit=None, accountStatus=None):
        """
        :param id: (Optional) 索引id
        :param userPin: (Optional) 用户名
        :param accountId: (Optional) 账户ID
        :param serviceIp: (Optional) 提供httpdns服务的IP
        :param key: (Optional) httpdns服务的密钥
        :param keyStatus: (Optional) httpdns服务的密钥的状态，同key的序号对应
        :param createTime: (Optional) 账户创建时间
        :param updateTime: (Optional) 账户更新时间
        :param noauthAccess: (Optional) 非鉴权方式是否可以访问httpdns服务，0:不可以，1:可以
        :param domainLimit: (Optional) 账户最多可以创建的域名
        :param accountStatus: (Optional) 账户状态，0:正常 1:使用80%流量，2:欠费 3:停服
        """

        self.id = id
        self.userPin = userPin
        self.accountId = accountId
        self.serviceIp = serviceIp
        self.key = key
        self.keyStatus = keyStatus
        self.createTime = createTime
        self.updateTime = updateTime
        self.noauthAccess = noauthAccess
        self.domainLimit = domainLimit
        self.accountStatus = accountStatus
