# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class ImageDetectionTaskObject(object):

    def __init__(self, taskId=None, detectionType=None, input=None, output=None, status=None, resultData=None, errorMessage=None, createTime=None, updateTime=None, finishTime=None):
        """
        :param taskId: (Optional) 任务ID
        :param detectionType: (Optional) 检测类型
        :param input: (Optional) 
        :param output: (Optional) 
        :param status: (Optional) 任务状态。
- pending：待处理
- processing：处理中
- success：处理成功
- failed：处理失败

        :param resultData: (Optional) 检测结果数据（JSON，任务完成后有值）
        :param errorMessage: (Optional) 错误信息
        :param createTime: (Optional) 创建时间
        :param updateTime: (Optional) 更新时间
        :param finishTime: (Optional) 完成时间
        """

        self.taskId = taskId
        self.detectionType = detectionType
        self.input = input
        self.output = output
        self.status = status
        self.resultData = resultData
        self.errorMessage = errorMessage
        self.createTime = createTime
        self.updateTime = updateTime
        self.finishTime = finishTime
