# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class TranscodeNodeParam(object):

    def __init__(self, accessKey=None, secretKey=None, endpoint=None, title=None, templateId=None, outputConfig=None, additionalProperties=None):
        """
        :param accessKey: (Optional) 地域
        :param secretKey: (Optional) 
        :param endpoint: (Optional) 路径
        :param title: (Optional) 模版id
        :param templateId: (Optional) 模版id
        :param outputConfig: (Optional) 输出配置
        :param additionalProperties: (Optional) 
        """

        self.accessKey = accessKey
        self.secretKey = secretKey
        self.endpoint = endpoint
        self.title = title
        self.templateId = templateId
        self.outputConfig = outputConfig
        self.additionalProperties = additionalProperties
